### ISSUE TITLE
marginalmeans() for glmmTMB Beta models

### ISSUE THREAD

**Issue by DominiqueMakowski** [vincentarelbundock/marginaleffects#1002]
Hi Vincent, 

This is likely related to: https://github.com/glmmTMB/glmmTMB/issues/915

``` r
dat <- data.frame(y = runif(100, 0.001, 0.999),  
                  x = sample(c("C1", "C2"), 100, replace = TRUE),
                  group = sample(c("A", "B", "C"), 100, replace = TRUE)) 

m <- glmmTMB::glmmTMB(y ~ x + (1|group), data=dat, family=glmmTMB::beta_family(link = "logit"))


marginaleffects::marginalmeans(m)
#> Error: By default, standard errors for models of class `glmmTMB` are not
#>   calculated. For further details, see discussion at
#>   {https://github.com/glmmTMB/glmmTMB/issues/915}.
#>   Set `vcov = FALSE` or explicitly provide a variance-covariance-matrix
#>   for the `vcov` argument to calculate standard errors.


marginaleffects::marginalmeans(m, vcov = vcov(m))
#> Error in isTRUE(vcov == FALSE): 'list' object cannot be coerced to type 'logical'
```

<sup>Created on 2024-01-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Passing the output of a `vcov` function or the function itself `vcov=stats::vcov` throws an error, is this expected?

**Comment by vincentarelbundock** [comment]
That's because `vcov()` does not return a matrix for `glmmTMB` objects. It's a list with potentially multiple vcovs, so you need to pick one and only supply the matrix: `vcov(model)$cond`.

That said, the error is there for a reason, and I'm not sure you should use `marginaleffects` with this package right now. See https://github.com/vincentarelbundock/marginaleffects/issues/810

I'm pretty sure I know the solution, but it would require major refactor which would take several hours of work, and I don't have the time right now. 

https://github.com/glmmTMB/glmmTMB/issues/915

**Comment by vincentarelbundock** [comment]
BTW, I am gearing up for version 1.0.0 with the last round of deprecations until the API is stabilized. The `marginal_means()` function will be deprecated in favor of:

```r
predictions(mod, newdata = datagrid(grid_type="balanced"), by = "x")
```

Of course, the `marginal_means()` function will still work for a while, but don't be surprised if it starts raising a warning soon.

**Comment by vincentarelbundock** [comment]
Closing as duplicate
