### ISSUE TITLE
Name format vs output variation? 

### ISSUE THREAD

**Issue by Lefty2021** [vincentarelbundock/marginaleffects#1005]
If the name of a "variable" change to \`name of variable\` (e.g. in mtcars from "hp" to \`horse power\`) the plot_predictions will result outcome with higher uncertainty eg

d1 <- mtcars %>% as_tibble
d2 <- d1 %>% rename(\`horse power\` = hp)

m1 <- lm(mpg ~ hp, data = d1)
m2 <- lm(mpg ~ \`horse power\`, data = d2)
sjPlot::tab_model(m1, m2)

p1 <- plot_predictions(m1, condition = 'hp')
p2 <- plot_predictions(m2, condition = 'horse power')
p1 + p2

![image](https://github.com/vincentarelbundock/marginaleffects/assets/88385159/1ce2ad75-17ea-4332-a8c6-09ff67c2838e)

Notice that the data is the same and the model are identical.

**Comment by vincentarelbundock** [comment]
Thanks a lot for raising this issue. I really appreciate that you took the time to craft a useful minimal example.

I believe that this bug is related to this line of code: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_se_delta.R#L87

I'll think of a solution when I have a minute.

**Comment by Lefty2021** [comment]
Thanks for this awesome package!

**Comment by vincentarelbundock** [comment]
This should now be fixed on Github. I'll release the fix to CRAN very soon.

Thanks again for raising this issue with a nice reproducible example. Very useful!
