### ISSUE TITLE
support for distributional models in 'brms'?

### ISSUE THREAD

**Issue by TenanATC** [vincentarelbundock/marginaleffects#1036]
Is it possible to add support for distributional models in 'brms'?  Specifically, it would be nice to plot and make analyses for 'sigma' and 'phi' when they are modeled within the original model.  Is it possible to integrate this support from the 'brmsmargins' package into the 'marginaleffects' ecosystem?

**Comment by vincentarelbundock** [comment]
If you supply a minimal working example with a public dataset like `iris` or `mtcars`, I can look into it.

**Comment by vincentarelbundock** [comment]
Aah, I see what you mean. I think this is already supported, because we can always pass extra arguments to the prediction functions in `brms`. Since that package supports a `dpar` argument, we can just name `sigma` explicitly. See this example where I make predictions on something called `hu`: https://marginaleffects.com/vignettes/brms.html#adjusted-predictions-2
