### ISSUE TITLE
Why the difference between marginaleffects::plot_predictions and sjPlot::plot_model for prediction plots?

### ISSUE THREAD

**Issue by bshor** [vincentarelbundock/marginaleffects#1042]
I'm estimating a multilevel model with lme4. Previously, I'd visualize a conditional prediction plot with the sjPlot package's plot_model function. I've been experimenting with plot_predictions from marginaleffects and noticing difference in how the intercept is calculated, and I don't understand why.

First, here's the visualizations from each package. Notice the slope is the same, but the intercept looks quite different.

![image](https://github.com/vincentarelbundock/marginaleffects/assets/468070/81714dcc-d976-4342-a12f-fbc5417d43d0)

The code to produce these visualizations:

```
  me <- plot_predictions(fit.roll.2model.styr[["r"]],condition=c("diff"))+
    theme_bw()+coord_cartesian(xlim=c(-0.4,0.4), ylim=c(0,.10)) +
    labs(title="marginaleffects plot_predictions conditional on diff")
  
  sj <- plot_model(fit.roll.2model.styr[["r"]],type="pred",terms=c("diff"))+
    theme_bw()+coord_cartesian(xlim=c(-0.4,0.4), ylim=c(0,.10))+
    labs(title="sjPlot plot_model conditional on diff")
```

And the model coefficients that underlay this visualization:

![image](https://github.com/vincentarelbundock/marginaleffects/assets/468070/761c8603-9cf7-4cd1-bcaa-016d5f6e2b48)

Can somebody explain why the differences between these two packages' prediction plots?

**Comment by vincentarelbundock** [comment]
The two functions are probably holding constant the unit variable to a different category. You can use draw=FALSE to see which one plot_predictions() uses by default. 

But really, in these models you probably what to be more explicit about exactly which units you want to make predictions, rather than relynon the defaults of any software, sjPlot, marginaleffects, or other.

If you read the documentation for plot_predictions(), and the vignette on plotting, you'll see there are many approaches to be more explicit. The vignette on mixed models with lme4 could also be helpful.

**Comment by andrewheiss** [comment]
See this for some more examples and a comparison of a bunch of different ways of dealing with the random effects: <https://www.andrewheiss.com/blog/2022/11/29/conditional-marginal-marginaleffects/>

**Comment by vincentarelbundock** [comment]
closing to cleanup the repo, but feel free to comment again if investigate more or can provide a minimal reproducible example
