### ISSUE TITLE
relation to effects package?

### ISSUE THREAD

**Issue by friendly** [vincentarelbundock/marginaleffects#105]
You should describe in docs or examples how this differs from the computations and plots available in the `effects` package

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion!

I am not super familiar with the `effects` package, but I know it can draw a lot of different plots. I'm not sure I have the bandwidth to do plot-by-plot comparisons with all alternative packages (there are many).

What specific plots do you recommend I target for comparison, given limited time.

**Comment by friendly** [comment]
Check out the `effects::Effect` function and associated plot methods.  It is similar to your marginaleffects, and has methods for a slew of different models.

**Comment by vincentarelbundock** [comment]
Thanks @friendly,  that's helpful!

I skimmed the `effects` package vignettes, and I believe that these are the core differences relative to `marginaleffects`:

+ `effects` only supports plots of [what I call "Adjusted Predictions."](https://vincentarelbundock.github.io/marginaleffects/articles/predictions.html) The plots it produces seem roughly equivalent to the ones produced by my `plot_cap` function.
+ `effects` does not support marginal effects (slopes) or marginal means. AFAICT, it cannot draw plots like `plot_cme`, or generate the same results as the `marginaleffects` and `marginalmeans` functions.
+ `effects` uses Base graphics whereas `marginaleffects` uses `ggplot2`
+ `marginaleffects` supports about 30 more model types than `effects`, although there are still a few which are still supported by `effects` but not `marginaleffects` (e.g., `clm`, `clm2`, `glmmPQL`, `robustlmm::rlmer`).
+ `effects` includes *a lot* of very powerful options to customize plots. In contrast, `marginaleffects` produces objects which can be customized by chaining `ggplot2` functions. The plotting functions are unlikely to become much more sophisticated, because my expectation is that users who want even more complex plots will call `plot_cap(model, draw=FALSE)` and work with the plotting data directly.

I think that the above is accurate, but I will review the `effects` documentation more carefully to be sure what I write is fair and accurate.
 
I plan to write a vignette with explicit comparisons to the main alternative packages, including `effects`, and I will ping you if/when I get around to it.

Thanks again for the nudge! I agree that it's very important that potential users understand clearly the differences between alternatives.
