### ISSUE TITLE
Support: sdmTMB

### ISSUE THREAD

**Issue by sschooler** [vincentarelbundock/marginaleffects#1136]
https://pbs-assess.github.io/sdmTMB/index.html

It works through a similar method as glmmTMB, but it does have the spatial/temporal random fields, which may make it harder to deal with. It supposedly functions with emmeans, but I've been running into the "contrasts can only be applied to factors with 2 or more levels" error.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. I'll try to look into it if/when I have time.

**Comment by vincentarelbundock** [comment]
Closing this issue, not because I am not interested (I am!), but because all model support requests are consolidated in the linked thread to keep the list of issues more manageable.

I would be glad to review Pull Requests, and will try to have a look when I can (but my day job keeps me very busy these days).
