### ISSUE TITLE
`plot_*()`: Support different `scales` arguments in `facet_wrap()` from `ggplot2`

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/marginaleffects#1149]
Small feature request: When plotting functions return small multiples (e.g., due to a `variables` argument with length > 1) I think it would be great to have the option to align the plots vertically and have common axes in order to facilitate their comparison. 

I was not able to force this alignment with ggplot's `ylim` nor by using the patchwork package. Recreating the plot by hand using `draw = FALSE` was my only successful attempt so far:

``` r
library(tidyverse)
library(palmerpenguins)
library(marginaleffects)

dat <- penguins |> 
  mutate(
    d1 = sample(c(0, 1), size = nrow(penguins), replace = TRUE),
    d2 = sample(c(0, 1), size = nrow(penguins), replace = TRUE)
  )

mod <- lm(body_mass_g ~ d1 * bill_length_mm + d2 * bill_length_mm, data = dat)

# plots not horizontally aligned
plot_slopes(
  mod, 
  variables = c("d1", "d2"),
  condition = "bill_length_mm"
)
```

![](https://i.imgur.com/uja00tT.png)

``` r

# plot individually

p1 <- plot_slopes(
  mod, 
  variables = "d1",
  condition = "bill_length_mm"
)

p2 <- plot_slopes(
  mod, 
  variables = "d2",
  condition = "bill_length_mm"
)

# patchwork does not align either
library(patchwork)

p1 + p2
```

![](https://i.imgur.com/YpY2UD3.png)

``` r
p1 + p2 + plot_layout(guides = "collect")
```

![](https://i.imgur.com/rHaem1Q.png)

``` r

# manual plot with facet_wrap works
raw <- plot_slopes(
  mod, 
  variables = c("d1", "d2"),
  condition = "bill_length_mm",
  draw = FALSE
)

ggplot(raw, aes(x = bill_length_mm)) +
  geom_line(aes(y = estimate)) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              alpha = 0.1) +
  facet_wrap(~term)
```

![](https://i.imgur.com/zjqFJVh.png)

<sup>Created on 2024-06-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for the feature request, @turbanisch. The reason you get this result is that internally we call `facet_wrap()` with the `scales="free"` argument. This is hard-coded, and there are currently no argument to change it.

At this point, I do not plan to add an argument for this. The reason is that `facet_wrap()` has 13 arguments, `geom_point()` 7 arguments, `geom_ribbon()` 10 arguments, etc. It is not a good idea to support all the `ggplot2` options, and it's a slippery slope to start making judgments about which arguments are too "niche", and those that are "popular" enough to be included.

Therefore, I made the decision to offer a basic set of customization options, and a `draw` argument that makes it trivial to get the underlying. As you post shows, it is very easy to re-create the plot you want by calling `draw=FALSE` and a few lines of `ggplot2`.

Sorry to disappoint.

**Comment by turbanisch** [comment]
Very understandable, thanks for letting me know that I'm on the right track then! 🙏
