### ISSUE TITLE
Support for dpar = "sigma" with glmmTMB models

### ISSUE THREAD

**Issue by ASKurz** [vincentarelbundock/marginaleffects#1191]
Here's an example of what I'd like to do:

```{r}
# Load packages
library(tidyverse)
library(glmmTMB)
library(marginaleffects)

# Simulate Gaussian data with conditional `sd`
n_group <- 250

set.seed(1)

d <- tibble(tx = rep(0:1, each = n_group)) |> 
  mutate(y = ifelse(tx == 0,
                    rnorm(n = n(), mean = 0, sd = 1),
                    rnorm(n = n(), mean = 0, sd = 2)))

# Fit a model with `glmmTMB()`
fit1 <- glmmTMB(
  data = d,
  y ~ 1 + tx,
  dispformula = ~ 1 + tx
)

# Compute a distributional estimand
avg_comparisons(fit1, dpar = "sigma")
```

The warning message includes the following:

> Warning: These arguments are not known to be supported for models of class `glmmTMB`: dpar. These arguments are known to be valid: re.form, allow.new.levels, zitype.

This example is a special case of what's really a broader request. It would be great if `avg_comparisons()` and related functions allowed for distributional estimands from a variety of `glmmTMB()` models.

**Comment by vincentarelbundock** [comment]
Hi @ASKurz,

I believe this is a limitation of `glmmTMB`. If the `dpar` argument is not supported by the `predict.glmmTMB()` method of that package, `marginaleffects` will never be able to support that feature.

In `brms`, the `posterior_epred()` functions supports the `dpar` argument, but this is not the case for `glmmTMB`. In your example, it looks like the `dpar` argument does not return different results. It only issues a warning and returns the same predictions:

``` r
library(tidyverse)
library(glmmTMB)
n_group <- 250
set.seed(1)
d <- tibble(tx = rep(0:1, each = n_group)) |> 
  mutate(y = ifelse(tx == 0,
                    rnorm(n = n(), mean = 0, sd = 1),
                    rnorm(n = n(), mean = 0, sd = 2)))
fit1 <- glmmTMB(
  data = d,
  y ~ 1 + tx,
  dispformula = ~ 1 + tx
)
p1 = predict(fit1, dpar = "sigma") 
# Warning in check_dots(..., .action = "warning"): unknown arguments: dpar
```

``` r
p2 = predict(fit1)

all.equal(p1, p2)
# [1] TRUE
```

Closing because this is an upstream limitation, but feel free to re-open if you think this is really within `marginaleffects`’s scope.
