### ISSUE TITLE
Deprecate `mlogit`

### ISSUE THREAD

**Issue by andrewheiss** [vincentarelbundock/marginaleffects#1216]
Back with https://github.com/vincentarelbundock/marginaleffects/issues/857, it was possible to use a `by` data frame to get predictions and do hypothesis tests with {mlogit}-based models, like so:

```r
library(tidyverse)
library(marginaleffects)
library(mlogit)
library(dfidx)

# Load example data
d <- read_csv("https://raw.githubusercontent.com/sangwoo-statistics/dataset/main/choco_candy.csv") %>% 
  mutate(
    dark = case_match(Dark, 0 ~ "Milk", 1 ~ "Dark"),
    dark = factor(dark, levels = c("Milk", "Dark")),
    soft = case_match(Soft, 0 ~ "Chewy", 1 ~ "Soft"),
    soft = factor(soft, levels = c("Chewy", "Soft")),
    nuts = case_match(Nuts, 0 ~ "No nuts", 1 ~ "Nuts"),
    nuts = factor(nuts, levels = c("No nuts", "Nuts"))
  )

# Make the data work with mlogit
d_idx <- dfidx(
  d,
  idx = list("Subj", "Alt"),
  choice = "Choice",
  shape = "long"
)

# Model with mlogit
m_mlogit <- mlogit(
  Choice ~ dark + soft + nuts | 0 | 0, 
  data = d_idx
)
m_mlogit
#> 
#> Call:
#> mlogit(formula = Choice ~ dark + soft + nuts | 0 | 0, data = d_idx,     method = "nr")
#> 
#> Coefficients:
#> darkDark  softSoft  nutsNuts  
#>   1.3863   -2.1972    0.8473
```

In August 2023, this worked (via https://github.com/vincentarelbundock/marginaleffects/issues/857#issuecomment-1667106925):

```r
by <- data.frame(by = c("Milk", "Dark"), dark = c("Milk", "Dark"))

predictions(
  m_mlogit,
  by = by
)
#
#   By Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
# Milk     0.05     0.0316 1.58    0.114  3.1 -0.012  0.112
# Dark     0.20     0.0316 6.32   <0.001 31.9  0.138  0.262
#
# Type:  response 
# Columns: estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, by 

predictions(
  m_mlogit,
  by = by,
  hypothesis = "revpairwise"
)
# 
#         Term Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %
#  Dark - Milk     0.15     0.0632 2.37   0.0177 5.8 0.026  0.274
# 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

As of {marginaleffects} 0.22.0, though, `predictions()` by itself still works, but `predictions()` with the hypothesis argument returns 0 and NA:

```r
by <- data.frame(by = c("Milk", "Dark"), dark = c("Milk", "Dark"))

predictions(
  m_mlogit,
  by = by
)
#
#   By Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %
# Milk     0.05     0.0316 1.58    0.114  3.1 -0.012  0.112
# Dark     0.20     0.0316 6.32   <0.001 31.9  0.138  0.262
#
# Type:  response 
# Columns: estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, by 

predictions(
  m_mlogit,
  by = by,
  hypothesis = "revpairwise"
)
# 
#  Estimate Std. Error  z Pr(>|z|)  S 2.5 % 97.5 %
#         0         NA NA       NA NA    NA     NA
# 
# Term: Dark - Milk
# Type:  response 
# Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

Has something changed with mlogit predictions in recent updates? Or has the `by` syntax changed?

**Comment by vincentarelbundock** [comment]
Sorry for this.

It appears to be yet another indexing problem related to handling separate rows in `mlogit`. Specifically here:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_mlogit.R#L13

which makes it so that `rowid` is not compatible when we try to merge `x` and `newdata` here: 

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_hypothesis.R#L34

Frankly, I think I might just deprecate support for `mlogit`. It is the *only* model supported by `marginaleffects` with this structure: multiple rows per observation. It has given me a ton of aggravation; more than any other. I can't figure out how to robustly align the rows generated by `predict()` to the rows in the original data for merging. And I still don't have an implementation I am confident in. Frankly, the current code feels kind of dangerous...

**Comment by vincentarelbundock** [comment]
TBC, this is not the fault of `mlogit`. It just uses a very different data structure than all the other models supported by `marginaleffects`, so it really complicates things.

**Comment by andrewheiss** [comment]
Yeah, I'm fine deprecating it—it's a weird kind of model and hard to work with, and I personally never use it :)

My only little worry is that it's still popular for frequentistly analyzing conjoint experiments and is still taught in marketing textbooks (like one popular one from 2019). [In this blog post](https://www.andrewheiss.com/blog/2023/08/12/conjoint-multilevel-multinomial-guide/#the-model-1) I compare it with Bayesian {brms}-based results, and {brms} works just fine with syntax like this:

```r
brm(
  bf(choice_alt ~ 0 + seat + cargo + eng + price + (1 | ID | resp.id)),
  data = minivans_choice_alt,
  family = categorical(refcat = "0"),
  ...
)
```

The data is still one-row-per-observation-choice, but {brms} and Stan's `categorical` family handles it all in a standard way that {marginaleffects} and {tidybayes} are happy with.

I'll poke around to see if {nnet} or something else can work with this kind of data frequentistly. If not, everyone can convert to Bayesianism :)

**Comment by vincentarelbundock** [comment]
Thanks for the input. Deprecated in 9778eef3ad98369c6e8d11ba7e894111ae6b4e94

> I'll poke around to see if {nnet} or something else can work with this kind of data frequentistly. If not, everyone can convert to Bayesianism :)

:-)

**Comment by fabianhaggerty** [comment]
A small remark: 
I understand the problem with `mlogit`.
But I just wanted to point out that there are people who have used `marginaleffects `for `mlogit `models in the past.
Particularly for teaching statistical courses it was very practical, because it was easy to implement and easy to explain to the students. (Especially if the entire course is based on frequentist rather than Bayesian statistics).
As long as **all (!)** independent variables of the model were specified in the `newdata `argument, the predicted probabilities were all correct. (I created a dataframe where each X variable is a column with the specified value(s) and each unique row is repeated as often as there are different alternatives in the mlogit model).
At least this is true for version `0.21.0`. It is true that if you omit an X variable that was part of the model from `newdata`, the values are incorrect.
I found this out by doing the same calculation in Stata.

I think it would be better if `mlogit `models could be used again, but with the message printed that one should be very careful when using these model and that the output values may be incorrect if the `predictions()` function is not handled correctly. Then its up to the user to decide wether to use (and trust) the estimated values.

**Comment by vincentarelbundock** [comment]
Thanks @fabianhaggerty I really appreciate your insight into this. Your point is well taken, but I do not plan to reinstate support.

The primary reason is the one you stated: It is dangerous because results can easily be incorrect. And since very few users actually read software warning and messages, I'm not sure those are sufficient.

The secondary reason, though, is almost as important: it was a big pain to maintain, and I want to conserve developer effort and time.
