### ISSUE TITLE
Testing systemfit objects uses z test where F tests would be more appropriate

### ISSUE THREAD

**Issue by mronkko** [vincentarelbundock/marginaleffects#1242]
Relates to #1233 

```
library(car)
library(systemfit)
library(marginaleffects)

set.seed(12345)
N <- 100
C <- matrix(c(1, .3, .3,
              .3,  1, .3,
              .3, .3,  1), 3, 3)
colnames(C) <- rownames(C) <- c("x1", "x2", "x3")
data <- as.data.frame(mvrnorm(N, rep(0, 3), C))
sys <- with(data, {
  y1 <- 2 * x1 + 3 * x2 + x3 + 10 * rnorm(N)
  m1 <- lm(y1 ~ x1 + x2 + x3)
  y2 <- x1 + 3 * x2 + 2 * x3 + 10 * rnorm(N)
  m2 <- lm(y2 ~ x1 + x2 + x3)
  systemfit(list(formula(m1), formula(m2)), data = data)
})
h <- hypotheses(sys)

# This works
hypotheses(sys, "b3 = b7")

# This works
linearHypothesis(sys, "eq1_x2 = eq2_x2")

```

The car package and marginaleffects produce different tests results. The model is estimated with OLS and therefore F test would be more appropriate for multiple hypothesis tests. However, in this case marginaleffects uses z test. Either t or F should be used instead when the estimates are from OLS.

**Comment by ngreifer** [comment]
Note this is because the `linearHypothesis()` method for `systemfit` objects, which is defined in the `systemfit` package and not the `car` package, uses a special method of computing the F-statistic by default that is specific to `systemfit` objects. Setting `test = "F"` in `linearHypothesis()` yields the same p-value and equivalent test statistic as `hypotheses()` (i.e., the F-statistic is the square of the z-statistic, as expected, with a slight difference due to df). It's only because `systemfit` uses a very specific test, Theil's F-test, by default that you see a discrepancy. Given that this is a highly specialized test implemented only in the `systemfit` package and `marginaleffects` is designed to be a general-purpose package, I don't think this would fit in `marginaleffects`, though Vincent might disagree. There will always be specialized tests designed for individual methods that might perform better than the general test; you should use those when possible if you understand why they are being used and under what circumstances they are to be preferred.

**Comment by vincentarelbundock** [comment]
Thanks @mronkko for raising this issue.

And thanks to @ngreifer for the investigation. I agree with you that `marginaleffects` cannot be expected to implement specialized tests relevant to a small subset of models. I will thus close this issue as "won't fix". Sorry to disappoint.
