### ISSUE TITLE
Degrees of freedom: Automatic + t stat

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1251]
Currently, `marginaleffects` reports $z$ statistics and computes $p$ values using `pnorm()`. Should we try to extract the residual degrees of freedom automatically and report $t$ statistics instead?

We could do this by writing a `sanitize_df()` function and calling this the top of our main functions.

```{r}
sanitize_df <- function(model) {
  if (is.null(df)) {
    df <- tryCatch(insight::get_df(model, type = "residual"), error = function(e) NULL)
  }
  return(df)
}
```

This function would default to `NULL` in case of error, which reverts us to $z$.

This was suggested by @mattansb

**Comment by vincentarelbundock** [comment]
@ngreifer related to our discussion https://github.com/vincentarelbundock/marginaleffects/issues/1242

Do you see any downside of this approach?

**Comment by mattansb** [comment]
Would also be nice to have native support for Kenward-Roger / Satterthwaite dfs for mixed models (Some nice code to get those in `emmeans:::emm_basis.merMod()`) ;)

**Comment by vincentarelbundock** [comment]
@mattansb K-R and S are already supported. See the `vcov` argument in all functions and the documentation here: https://marginaleffects.com/r/man/predictions.html#arguments

**Comment by mattansb** [comment]
Ohhhh I missed that!

**Comment by mattansb** [comment]
> Do you see any downside of this approach?

Downside: this gives df for glms (which don't really "need" them?)

```r
mod <- glm(am ~ hp, binomial, mtcars)

insight::get_df(mod, type = "residual")
#> [1] 30
```

**Comment by ngreifer** [comment]
I agree with @mattansb that is this is too broad an approach because it gives GLMs a finite df, which would imply a t-test. I'm not expert on this but I think only linear models can be tested with t-statistics. In `clarify`, I have the following function which is used to decide whether to use a t-distribution or z-distribution:

https://github.com/ngreifer/clarify/blob/a4e59ea5a9460ae11d5968a6981e92a2de6d23fd/R/get_model_components.R#L26-L42

I don't remember where I found that code, but I think it does the job. Feel free to use it or something like it.

**Comment by vincentarelbundock** [comment]
Yeah, that all makes. Thanks both form the input!

**Comment by mattansb** [comment]
Noah's function could be a great default here as well IMO
