### ISSUE TITLE
Book source?

### ISSUE THREAD

**Issue by jsr-p** [vincentarelbundock/marginaleffects#1253]
Hi

Thanks for the great package and [book](https://marginaleffects.com)!
I cannot find the source code for the book chapters; I found an error and would like to contribute.
Where are the source (qmd) files located?
Or can I only file issues?

cheers!

**Comment by vincentarelbundock** [comment]
Thanks a lot for your interest, I really appreciate it!

I would love any corrections or suggestions. Unfortunately, I can't share the source code for the book, because it is under contract with a publisher.

**_The book will always be published for free as a website,_** but the PDF and source code must be kept private, unfortunately.

If you can point to the errors here or by email, that would still be great, of course.

**Comment by jsr-p** [comment]
Totally understandable!
And thanks for the answer.

The issues is in the [Group-average marginal effect](https://marginaleffects.com/chapters/slopes.html#group-average-marginal-effect) section of the slopes chapter.
You write
> This is equivalent to manually taking the mean of the observation-level
> marginal effect for each species sub-group:
and compute

```R
aggregate(estimate ~ incentive, FUN = mean, data = slo)
```

where `slo` is the object just computed using the `avg_slopes` function.
The data inside `slo` is already aggregated by `incentive` so using the
`aggregate` function on it and getting the same values is not suprising :=)
I think you meant to use a non-aggregated `slopes` object:

```R
slo <- slopes(mod, variables = "distance")
aggregate(estimate ~ incentive, FUN = mean, data = slo)
```

**Comment by vincentarelbundock** [comment]
lol yes, you're right of course.

I'll fix this in the next release.

Thanks for taking the time!

**Comment by jsr-p** [comment]
No problem and likewise!
And again, great book + packages; learning a lot and saving a lot of time using your packages, thanks again! :smile:
