### ISSUE TITLE
sanity_dots too stringent

### ISSUE THREAD

**Issue by DominiqueMakowski** [vincentarelbundock/marginaleffects#225]
Because of the strict `sanity_dots`, any functions using marginaleffects as a backend (e.g., modelbased or user-made functions) that wants to allow some flexibility through `...` will fail. Can we maybe add an argument to bypass the sanity check? 

e.g., in https://github.com/easystats/modelbased/blob/master/R/get_marginaleffects.R#L41

``` r
model <- lm(Sepal.Width ~ Species * Petal.Length, data = iris)

modelbased::get_marginaleffects(model, trend = "Petal.Length", at = "Species") # works normally
#>   rowid     type         term      dydx  std.error    Species Petal.Length
#> 1     1 response Petal.Length 0.3878739 0.26016778     setosa        3.758
#> 2     2 response Petal.Length 0.3743068 0.09614966 versicolor        3.758
#> 3     3 response Petal.Length 0.2343482 0.08186667  virginica        3.758

modelbased::get_marginaleffects(model, trend = "Petal.Length", at = "Species", length = 10)
#> Error in sanity_dots(model = model, ...): These arguments are not supported for models of class lm: length. Please file a request on Github if you believe that additional arguments should be supported: https://github.com/vincentarelbundock/marginaleffects/issues
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Would it be satisfactory to change this error to a warning? You could either suppress it or catch it if you care about the message.

**Comment by vincentarelbundock** [comment]
Yeah, the error was way too aggressive. I switched it to a warning here: 92414ef

> For modelbased, that would work yeah (even though I'm a bit worried to have to silent all the warnings, as it's really just this one that is expected) 

You could always catch the warnings with `tryCatch` and decide what you want to return. I'm just not sure how I would introduce a switch for just this specific warning. The package must have 100 warning/error calls in `sanity_*()` functions. How granular should I go?

> And since it's common in R programming to allow for `...` arguments for safety (even if they don't do anything), I wonder what's the rationale behind the restriction 🤔

Right, I know this is quite common. In fact, I do it a ton in `{modelsummary}`. In that context, it's not a big deal because the worst that can happen is that your table is not colored or aligned properly, etc.

However, in applications where mission-critical statistical results can be affected by arguments, I actually think that silently absorbing unknown arguments into `...` is a *terrible* practice. Imagine if the user wants the population mean in a mixed-effects models and includes `re_form=NA`. That argument looks a lot like the "correct" one, but the results will *not* be what the user expects. That's a big problem.

BTW, methods like `predict.merMod()` and others do raise warnings in such cases.

I actually think that `insight` et al. should be *much* stricter than they currently are. Of course, we should be able to pass *internal* arguments to functions without triggering errors, but IMHO all user-level arguments should be checked and raise warnings if they are unknown. But that's a debate for another day ;-)

**Comment by DominiqueMakowski** [comment]
I see what you mean... it's good for best-practices enforcing, but as someone who creates a ton of convenience functions in my own scripts, silently absorbing `...` is pretty vital to maintain my sanity 😅

Anyway, thanks for the quick fix!

**Comment by vincentarelbundock** [comment]
Haha, yeah, I get it
