### ISSUE TITLE
Handling Sun & Abraham (2020) estimates stored in `fixest`-objects

### ISSUE THREAD

**Issue by fnaeher** [vincentarelbundock/marginaleffects#315]
While 'marginaleffects' usually handles `fixest`-objects well, the error message "Error in vcov[names(coefs), names(coefs), drop = FALSE] : Index out of range" is returned when trying to obtain mfx from Sun & Abraham (2020) estimates. The error might possibly be related to 'marginaleffects' not estimating averages of cohort marginal effects. However, the problem also persists if cohort effects are not averaged. In this case , "Error in get_predict.fixest(model = model, newdata = newdata_tmp, type = type,  : Unable to extract predictions from a model of type `fixest`" is returned although 'predictions' seems to work fine. Could a fix to the issues eventually be implemented? Replicable code:

data(base_stagg)

sunab.agg = feols(y ~ x1 + sunab(year_treated, year) | id + year, base_stagg)
marginaleffects(sunab.agg)
predictions(sunab.agg)

sunab.no_agg = feols(y ~ x1 + sunab(year_treated, year, no_agg = T) | id + year, base_stagg)
marginaleffects(sunab.no_agg)
predictions(sunab.no_agg)

Thank you very much!

**Comment by vincentarelbundock** [comment]
To be able to support a model, the modeling package that supplies the fitting function must also supply a `predict()` method that accepts a `newdata` argument to which we can pass a data.frame. It looks like `fixest` does not support that for aggregated Sun-Abraham models:

``` r
library(marginaleffects)
library(fixest)
data(base_stagg)

sunab.agg = feols(y ~ x1 + sunab(year_treated, year) | id + year, base_stagg)

sunab.no_agg = feols(y ~ x1 + sunab(year_treated, year, no_agg = T) | id + year, base_stagg)

predict(sunab.agg, newdata = base_stagg)
#> Error in mm_info_new[[i]]: subscript out of bounds
```

Using version 0.5.0 (make sure you restart R after installing), it looks like both commands now work for the not-aggregated

``` r
marginaleffects(sunab.no_agg) |> summary()
#> Average marginal effects 
#>           Term    Effect Std. Error z value   Pr(>|z|)     2.5 %   97.5 %
#> 1           x1    0.9947    0.01838  54.123 < 2.22e-16    0.9587    1.031
#> 2 year_treated 2841.4580  707.09524   4.018 5.8571e-05 1455.5768 4227.339
#> 
#> Model type:  fixest 
#> Prediction type:  response

predictions(sunab.no_agg) |> head(2)
#>   rowid     type  predicted  std.error   conf.low conf.high           y
#> 1     1 response -0.2554127 0.02011858 -0.2948444 -0.215981  0.01722971
#> 2     2 response -3.9162453 0.67234871 -5.2340245 -2.598466 -4.58084528
#>          x1 year_treated id year
#> 1 -1.094702            2 90    1
#> 2 -3.710068            3 89    1
```

This makes sense because the required `fixest` method also works:

``` r
predict(sunab.no_agg, newdata = base_stagg) |> head(2)
#> [1] -0.2554127 -3.9162453
```

**Comment by vincentarelbundock** [comment]
My expectation is that if/when this is fixed upstream in `fixest`, then `marginaleffects` should start working automatically. Since I don't expect to have to change anything here, I'll close the issue now.

Feel free to re-open this one or open a new issue if things don't work as expected.

Thanks for the suggestion!

**Comment by fnaeher** [comment]
Thank you very much for your quickly reply and support.
