### ISSUE TITLE
Support `timereg` or `coxphw` packages

### ISSUE THREAD

**Issue by FONDECYTACC** [vincentarelbundock/marginaleffects#467]
It would be great to extend it to weighted cox models such as those that are available in "timereg" or "coxphw" packages

**Comment by vincentarelbundock** [comment]
If you supply minimal examples with publicly available data, I would be happy to look into it.

**Comment by vincentarelbundock** [comment]
Unfortunately, I will not be able to add support for these packages in the short term.

`coxphw`: The `predict()` method associated to that package does not accept a `newdata` argument. The author of that package would have to add that functionality, otherwise `marginaleffects` will never be able to support it.

```r
library(coxphw)
data("biofeedback", package = "coxphw")
mod <- coxphw(Surv(yrs, status) ~ radiation, data = gastric, template = "PH", robust = TRUE)
predict(mod, type = "lp", newdata = head(biofeedback)) |> str()
```

`timereg`: The `predict()` produce a very idiosyncratic object type, instead of a simple vector or matrix like in most other modeling functions. I am not sure how to use that object, or if the `newdata` argument works as intended. If a `timereg` experts wants to prepare a pull request to add support in `marginaleffects`, I will be happy to guide them through the process, but I am unlikely to do this myself, because I don't know these objects well enough.

My guess is that the predictions are hosted in `S0` entry of the `predict()` output object, but I'm not sure.

```r
library(timereg)
data(sTRACE)
mod <- aalen(Surv(time, status == 9) ~ age + sex + diabetes + chf + vf, data = sTRACE, max.time = 7, n.sim = 100, resample.iid = 1)
predict(mod, newdata = head(sTRACE)) |> str()
```
