### ISSUE TITLE
Default `type` value?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#471]

**Comment by tomwenseleers** [comment]
In `emmeans `there is two types - the `type=XX` specified in the `emmeans `call, and then a `type=XX `in the `summary() `or `as.data.frame() `of that `emmeans `object. For binomial GLMs, `emmeans `uses as default in the `emmeans `call type="link", i.e. so that marginal means are calculated on the natural linear predictor link scale, but the summary or data frame of that object has as default `type="response"`, so that the predictions and confidence intervals are backtransformed to the original response scale. So for GLMs I would think that `marginaleffects `in `predictions() `should use type="link" as default, combined with the correct `transform_post ` inverse link transformation.

**Comment by vincentarelbundock** [comment]
When users call `predictions(model, type = "response")`, we *automatically* make predictions and build intervals on the link scale, and then backtransform them to get proper intervals. There is no need for users to specify the `transform_post` argument by hand, since we do the work for them. 

This works for a broad range of models, but not all of them. When we don't know what to do, we report delta method standard errors but don't build symmetric intervals, since those may not have great properties.

If we set a default `type` for all models, it will almost certainly be "response", since that is the most natural scale only which most researchers will want to interpret their results. Again, no need for the `emmeans` two-step, since we handle this behind the scenes.
