### ISSUE TITLE
Support `type="link"` for `nnet::multinom` models

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#477]
@tomwenseleers made a feature request to support `type="link"` in `nnet::multinom` models. I am very unlikely to implement this feature myself, because defining new prediction methods is out-of-scope for this project; I rely on the models' developer-supplied `predict()` methods. However, I would be happy to review and (potentially) merge a Pull Request if a contributor wants to work on this.

What this PR would need:

* Modify *only* three files:
    - `R/type_dictionary.R`
    - `R/methods_nnet.R`
    - `NEWS`
* All code in `get_predict()` goes under: `if(inherits(model, "multinom") && type == "link") {}`
* Create a model matrix by drawing inspiration from `predict.mblogit()` See https://github.com/vincentarelbundock/marginaleffects/issues/476
* Tests using the built-in `mtcars` dataset:
    - binomial vs multinomial outcome
    - one vs. multi-row `newdata`
    - model with factors/characters and numerics
    - model in-formula transformation
    - comparisons to `emmeans` for all these models
    - tests located in `inst/tinytest/test-pkg-nnet.R`
* Add info `NEWS`
* Follow the coding style of the repo, ex: arrow assignment, 4-space tabs, space around operators.

**Comment by tomwenseleers** [comment]
OK so have this almost working - I'm getting correct predictions now for `type="link"` and `type="latent"` for `nnet::multinom` models that mirror those of `mclogit::mblogit` models. The only thing that is not working yet is that `predictions()` with `nnet::multinom` models only return confidence intervals with `type="link"`, but not with `type="latent"` or `type="probs"`, while for `mclogit::mblogit` it returns confidence intervals for all 3 types (`"link"`, `"latent"` and `"response"`). Previously you told me "We return confidence intervals only for (1) linear models and (2) models for which we can predict on the link scale and backtransform to get proper intervals. In other cases, we supply a delta method standard errors, but we do not build symmetric intervals, because those may not always make sense.". I noticed `mblogit `models have as class `"mblogit"`, `"mclogit"` and `"lm"` - does that `"lm"` cause this difference in behaviour? (Adding `"lm"` as class for the `nnet::multinom` function didn't help though) What other method should be defined or functionality should be provided to make calculation of confidence intervals work for all 3 types for `nnet::multinom` models, in the same way that this works for `mclogit::mblogit` models?

**Comment by vincentarelbundock** [comment]
Great!

What happens if you type `insight::model_info(your_model)$is_linear`? Perhaps the class inheritance that you highlight produces an incorrect results with `model_info`. In that case, the problem would be with `mblogit`, which under current policy should *not* return CIs.

That said, I'm now thinking that current policy might be a bit too strict by  *not* computing confidence intervals for non-linear non-backtransformable models. Perhaps I should just compute the CI anyway and print a warning about CIs being "naive" and "symmetric".

What do you think?

**Comment by tomwenseleers** [comment]
Ha yes - it must have to do with that - even if I add class `"lm" `to a `nnet::multinom` model I get
```
> insight::model_info(fit_multinom)$is_linear
[1] FALSE
> insight::model_info(fit_mblogit)$is_linear
[1] TRUE
```

So it would indeed be the case that under currently policy, `mblogit `should in principle not return CIs.

But I think this is indeed too restrictive - I would indeed just return the symmetric Delta method CIs anyway, and leave it up to the user to decide if they are good enough and whether they make sense or not. Emmeans at least always returns CIs, even if they are symmetric Delta method based intervals. At the same type, based on predictions with `type="link"` one can get backtransformed asymmetric CIs on the response scale also for multinomial models as I showed here [https://github.com/vincentarelbundock/marginaleffects/issues/476](https://github.com/vincentarelbundock/marginaleffects/issues/476) (mentioned in the last message at the bottom of that post). These are the best ones in a way - as they give the exact same result as the backtransformed CIs for a binomial GLM when one has 2 outcome levels (and it would stick to the same logic with >2 outcome levels). The Delta method based CIs on the response scale are also really close (though they can occasionally go very slightly outside the allowed domain [0,1]). Also wondering if for type="link" and for both `mclogit::mblogit` and `nnet::multinom` models if it would not make sense to also return the predictions for the reference level explicitly as zero. If you like I can modify it to behave like that. Backtransforming from either the link or the latent scale to the response scale would then be as simple as taking the `softmax `(in a grouped way, by rowid).

**Comment by vincentarelbundock** [comment]
> ```
> > insight::model_info(fit_multinom)$is_linear
> [1] FALSE
> > insight::model_info(fit_mblogit)$is_linear
> [1] TRUE
> ```

Right. I think we should report this to the `insight` repository with a reproducible example using the `mtcars` data.

Agreed on CIs.

> Ha and should `type="probs"` not be harmonized to `type="response"` for `nnet::multinom` models, to match the notation in `mclogit::mblogit`?

In `insight`, they make a lot of efforts to harmonize. I think this is a very hard and perilous job, and decided early on that I would stick with the modeling package's vocabulary. This helps consistency with the modeling functions and simplifies my life.

**Comment by tomwenseleers** [comment]
OK sounds good! I can see your point re. harmonizing being difficult in the context of this package - though since I'm working anyway now on that `get_predict.multinom` wrapper it would be easy to have that fixed in this case. 

And for `type=="link"` - would you like me make the reference level come out as zero (now that level is dropped), or would you like me to leave that as it is (for both `mcclogit::mblogit` and `nnet::multinom` models)? If all outcome levels would come out it would facilitate backtransformation as then one just has to take the `softmax `transform grouped over `rowID`s to go back to the response scale, both for `type=="link"` and `type=="latent"` (otherwise one would still have to add that zero manually before backtransformation). What method has to be there to decide whether or not a given model is backtransformable (the inverse link function would have to be aware of `rowID `though to make this work)?

**Comment by tomwenseleers** [comment]
OK I'll leave it as it is then for now! I'll do a bit more testing & I'll then send you a PR so you can see what I did!

**Comment by vincentarelbundock** [comment]
Thanks!

**Comment by tomwenseleers** [comment]
Just sent you a pull request - `type="link"` (and all other types) seems to work as intended now: [https://github.com/vincentarelbundock/marginaleffects/pull/478](https://github.com/vincentarelbundock/marginaleffects/pull/478)

**Comment by vincentarelbundock** [comment]
Closing because there is now an open (but incomplete) PR: https://github.com/vincentarelbundock/marginaleffects/pull/478
