### ISSUE TITLE
`conf_level` does not change width of confidence intervals in `comparisons`

### ISSUE THREAD

**Issue by Dpananos** [vincentarelbundock/marginaleffects#502]
Minimal working example below, I think it is fairly self explanatory.

Would be happy to contribute to this if you could let me know where the problem is

``` r
library(tidyverse)
library(marginaleffects)

x_num <- 1 + rbinom(100, 1, 0.5)
x <- letters[x_num]
p <- 0.25 + 0.5*(x_num-1)
y <- rbinom(100, 1, p)

fit <- glm(y~x)

comparisons(fit, conf_level = 0.95) %>% 
  summary
#>   Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1    x    b - a 0.3879    0.09357   4.145 3.3936e-05 0.2045 0.5713
#> 
#> Model type:  glm 
#> Prediction type:  response

comparisons(fit, conf_level = 0.8) %>% 
  summary
#>   Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1    x    b - a 0.3879    0.09357   4.145 3.3936e-05 0.2045 0.5713
#> 
#> Model type:  glm 
#> Prediction type:  response
```

<sup>Created on 2022-10-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report\!

The issue is that the `tidy()` function (and thus the `summary()` function which calls `tidy()` behind the scenes) has a `conf_level` argument of its own, with a default value of .95:

``` r
library(tidyverse)
#> Warning in system("timedatectl", intern = TRUE): running command 'timedatectl'
#> had status 1
library(marginaleffects)

x_num <- 1 + rbinom(100, 1, 0.5)
x <- letters[x_num]
p <- 0.25 + 0.5*(x_num-1)
y <- rbinom(100, 1, p)
fit <- glm(y~x)

cmp <- comparisons(fit)

summary(cmp, conf_level = .95)
#>   Term Contrast Effect Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1    x    b - a 0.6089      0.082   7.426 1.1204e-13 0.4482 0.7696
#> 
#> Model type:  glm 
#> Prediction type:  response
summary(cmp, conf_level = .99)
#>   Term Contrast Effect Std. Error z value   Pr(>|z|)  0.5 % 99.5 %
#> 1    x    b - a 0.6089      0.082   7.426 1.1204e-13 0.3977 0.8202
#> 
#> Model type:  glm 
#> Prediction type:  response
```

One option would be to deprecate the `conf_level` in `tidy()`, save the alpha level as an attribute in the initial call, and have `tidy()` use that automatically.

However, I kind of like the flexibility of having this available at both “levels” – unit-level and aggregate – and we need to different confidence intervals machinery under the hood anyway. 

That said, I can see this why this can be confusing, and I'd be happy to consider recommendations for improvements in the user interface.

**Comment by vincentarelbundock** [comment]
One nice option might be to set `summary(x, conf_level=NULL)` and to use the level used in the original computation by default, while still allowing users to change it manually. Makes sense?

**Comment by Dpananos** [comment]
Yea I think that’s a great idea Cheers,DOn Oct 6, 2022, at 10:30 AM, Vincent Arel-Bundock ***@***.***> wrote:﻿
One nice option might be to set summary(x, conf_level=NULL) and to use the level used in the original computation by default, while still allowing users to change it manually. Makes sense?

**Comment by vincentarelbundock** [comment]
The `summary()` function in the dev version on Github should now inherit `conf_level` used in the original call.

Thanks for the suggestion!

cd9cc74c04a86e8a47fffb3da3927a0098ed1a2f
