### ISSUE TITLE
Handling of random effects in datagrid() and predictions()?

### ISSUE THREAD

**Issue by GatesDupont** [vincentarelbundock/marginaleffects#503]
I'm modelling temporal dynamics of bird abundance. The data are repeated counts at each site, where some sites report those repeated counts for multiple years, and there are many sites. I have a model of the form below:

```R
  m <- bam(
    
    count ~
      s(site, bs = "re") +
      s(year),
    
    family = poisson(),
    data = df)
```

I want to recover the average estimated count for each year from this model. Obviously, the model will have soaked up considerable variation through the site-level random effect, which is great. So, I think I want to marginalize out the effect of site: I'm not interested in how much variation there is among sites, and instead I'm interested in how sure I am of the mean count for each year (having already soaked up the site-level variations in the model).

Towards this endeavor, I tried to use the `predictions()` function for this, along with `datagrid()`:

```R
p <- predictions(
  model = m,
  newdata = datagrid(year = df$year))
```

However, when I do this, the function returns predictions for a specific site that it somehow selected (in this case, site 10). I don't really understand how `datagrid()` or perhaps `predictions()` is selecting a level (site 10) of the random effect (site). I can't find anything on the website for this either.

So, 1) could you describe how a site is being selected by these functions? and 2) is there a way to derive what I'm interested in (mean and certainty of population-level parameters)? 

Thank you.

**Comment by vincentarelbundock** [comment]
It would be easier to help with a minimal working example built using public data, but,

1. Please refer to the `datagrid()` documentation. When a variable is not defined explicitly, its value is picked by the `FUN_*` associated to its class. If `site` is a factor, for example, we pick the mode or an arbitrary most common value if there are multiple modes.
2. You could potentially use the `datagrid()` function to make predictions for each site, and then use the `by` argument to get yearly averages across sites.


Pseudo-code (since no MWE), using the very latest `marginaleffects` from Github:

```r
predictions(
  m,
  newdata = datagrid(year = unique, site = unique),
  by = "year")
```

**Comment by GatesDupont** [comment]
Many thanks for this. I would have liked to include an MWE, but the dataset is very large and not public. However, the info you provided is super helpful, and I'm thrilled to see it. 

The `predictions()` function takes quite a while though (running about ~10 minutes for ~700 sites and ~33 years of data). Are there ways to speed this up?

Thank you.

**Comment by vincentarelbundock** [comment]
> However, the info you provided is super helpful, and I'm thrilled to see it.

Great news!

> The `predictions()` function takes quite a while though (running about ~10 minutes for ~700 sites and ~33 years of data). Are there ways to speed this up?

Usually, the most expensive operation is to call `predict()` repeatedly, and I seem to recall that the predict function shipped by the package which is used to fit this specific type of model is particularly slow. (I can't do anything about that, unfortunately.)

The bulk of computation time is nearly always spent computing standard errors, since that requires us to call `predict()` twice for *every* coefficient in the model. You can try calling `predict(model, newdata = df)` to see how long it takes, and then multiply that by `2*(length(coef)+1)` to ballpark how long those unavoidable computations take.

If you don't need standard errors, setting `vcov=FALSE` will usually speed things up considerably.

**Comment by vincentarelbundock** [comment]
I'm cleaning the repo, and I'll close this issue since there doesn't seem to be anything actionable for me left.

However, I'd be quite interested in benchmarks or profiling for your model, especially if `vcov=FALSE` does *not* speed things up, or if `predictions()` is orders of magnitudes slower than `predict()` (say, more than 3x the number of coefficients).
