### ISSUE TITLE
pkgdown searchbar leads to broken links

### ISSUE THREAD

**Issue by mattansb** [vincentarelbundock/marginaleffects#538]
For some reason, results from the pkgdown searchbar lead to broken links. E.g.:
- Searching "contrasts" leads to https://vincentarelbundock.github.io/articles/contrasts.html?q=contrasts
- instead of https://vincentarelbundock.github.io/marginaleffects/articles/contrasts.html

**Comment by vincentarelbundock** [comment]
Wow, yes. Frankly, I don't `pkgdown` much, so I have no idea why the `marginaleffects` directory does not appear in the URL from the search bar.

Perhaps website-genius @IndrajeetPatil  would have an idea? ;-)

**Comment by IndrajeetPatil** [comment]
Hmm, strangely, the search results in URL that start with `https://vincentarelbundock.github.io/`, instead of `https://vincentarelbundock.github.io/marginaleffects/`. That's why everything is 404. Search for anything, not just "Contrasts", and it will result in a 404 error.

I am not sure if this will solve the issue, but it's a worth a try.  Try adding the following to `_pkgdown.yaml` [file](https://github.com/vincentarelbundock/marginaleffects/blob/main/_pkgdown.yml):

```yaml
url: https://vincentarelbundock.github.io/marginaleffects/
```

**Comment by vincentarelbundock** [comment]
@IndrajeetPatil That's it, you got it! Thanks for taking the time to look at this!
