### ISSUE TITLE
Problems with `get_predict()` and documentation

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#547]
Hi Vincent,

Wanted to raise a few issues about `get_predict()`, which I'm using in a package I'm working on.

- [ ]  First is that the documentation claims that the output is vector, but's it's actually a data.frame with `rowid` and `predicted` as the variable names, and occasionally `group` for multi-category/multivariate outcomes.

- [ ] Second is that the order of the columns is not standardized. For example, with multivariate `lm()`, the order is "rowid", "group", "predicted", but with univariate `lm()` the order is "predicted", "rowid".

- [ ] Third, for `mblogit` objects, the `type` argument doesn't accept `"prob"`, which it does for other multinomial models. This is probably an issue with `type_dictionary`.

Thanks!

Noah

**Comment by vincentarelbundock** [comment]
Thanks!

Fixed the documentation.

Fixed the order of columns in `lm` models and added a `sort_columns()` function in `R/utils.R` which might be convenient in the future. Some models may still be inconsistent, but we can fix them as we find them (this feels low-priority because people should never index by number anyway, so I won't revisit each model type individually now).

AFAICT, the method function supplied by the `mclogit` package does NOT support `"prob"` in its `type` argument. See `?mclogit:::predict.mblogit` Maybe `"response"` is what you are looking for? 

FWIW, I briefly considered make prediction types uniform across models, but quickly realized that this was not a business I wanted to be in at all, and that it was best to just use the names chosen by individual package developers, even at the cost of some inconsistency. I just don't want to litigate terminology in 60 different areas of statistics... (See `insight::get_predicted` for a good effort.)

**Comment by ngreifer** [comment]
I should have been more specific about `mblogit`. It's true that `predict.mblogit()` doesn't accept `"prob"`, but you have it as the default argument to `type` in `get_predict.mblogit()`. So it throws an error by default. Given that for other multinomial models, you return the probabilities by default, and `predictions()` etc. also request the predicted probabilities by default (without the user having to specify), it would seem to make sense for `get_predict.mblogit()` to also return the predicted probabilities by default. I initially thought this had to do with `type_dictionary` but it's actually just about the default argument.

**Comment by vincentarelbundock** [comment]
Ah, got it. Should now be fixed.

**Comment by vincentarelbundock** [comment]
But note that, internally, I always call `sanitize_type()` before `get_predict()`. So that might be something to consider for safer operation...
