### ISSUE TITLE
`predict.fixest` results in error

### ISSUE THREAD

**Issue by resulumit** [vincentarelbundock/marginaleffects#59]
I am very excited to see this package, especially because it provides support for `fixest` models. Thank you!

I have just noticed that there might be an issue with the `predict.fixest` function.

With the model used for the tests in the package...

```
mod = fixest::feglm(am ~ hp * wt | cyl, data = mtcars, family = "binomial")
```

...if we try to plot the conditional marginal effects with the `plot_cme` function...

```
plot_cme(mod, effect = "hp", condition = "wt")
```

... I receive the following error:

```
#> Error in predict.fixest(model, newdata = newdata, type = prediction_type) : 
#> The variable cyl is absent from the 'newdata' but is needed for prediction (it is a fixed-effect variable).
```

I receive the same error using `fixest::feols` and/or different datasets.

`fixest` version 0.9.0; `marginaleffects` 0.0.0.9000; all other packages updated and the session restarted before running the above code.

**Comment by vincentarelbundock** [comment]
Thanks for the report, this is super useful!

The problem is that `plot_cme` sets all the other variables -- except `hp` and `wt` -- to their means (for numeric) or modes (factors or logical). In this case, your cluster variable `cyl` is numeric, so its mean is taken. But obviously that won't work when `fixest` tries to make a prediction, because there is no cluster named `6.1248`.

The solution is to convert the `cyl` variable to factor before fitting the model.

In the new Github version I included some code to provide an informative warning to users when they run into this issue.

Also, note that the conditional marginal effects plot looks *super* weird in your `mtcars` example (especially with `am` as DV). My best guess is that the size of dydx is so small that all we see is noise from the numerical approximation. But if you simulate data with a fixed effects and interaction structure, the plot looks very reasonable:

``` r
library(marginaleffects)

# simulate
fe <- data.frame(unit = 1:25, fe = rnorm(25))
dat <- expand.grid(unit = 1:25, time = 1:50)
dat <- merge(dat, fe, by = "unit")
dat$x <- rnorm(nrow(dat)) + dat$fe
dat$w <- rnorm(nrow(dat))
dat$y <- dat$x + dat$w + dat$x * dat$w + dat$fe + rnorm(nrow(dat), sd = 10)

# this produces a warning
mod1 <- fixest::feols(y ~ x * w | unit, data = dat)
plot_cme(mod1, effect = "x", condition = "w")
#> Warning in prep_counterfactual_typical(..., model = model, data = data): Unless
#> otherwise instructed, this function sets numeric variables to their mean. This
#> is probably inappropriate in the case of cluster variables such as "unit". A
#> safer strategy is to convert cluster variables to factors before fitting the
#> model.
```

``` r

# this works
dat2 <- dat
dat2$unit <- as.factor(dat2$unit)
mod2 <- fixest::feols(y ~ x * w | unit, data = dat2)
plot_cme(mod2, effect = "x", condition = "w")
```

![](https://i.imgur.com/E1muOBH.png)

**Comment by resulumit** [comment]
Thank you very much for looking into this, and for your detailed response. I confirm that this addresses the issue.
