### ISSUE TITLE
Support: `metafor` (`rma`, `rma.mv`)

### ISSUE THREAD

**Issue by zacrobinson5** [vincentarelbundock/marginaleffects#604]
Recently tried to use the `marginaleffects` package to extract slopes from a multi-level model in the `metafor` package (`rma.mv` object) but looks like the model isn't currently supported so I followed the instructions to drop a comment here. I believe the function `predict()` works as needed

Sincerely appreciated!

**Comment by vincentarelbundock** [comment]
Thanks for taking the time to open an issue, and thanks for the suggestion.

I looked into this and AFAICT, the `predict()` methods in the `metafor` package do not have a `newdata` argument (probably because this is very different from a “typical” model-fitting package). Unfortunately, this means I won’t be able to add support for it.

To see why, note that the entire infrastructure that drives `marginaleffects` is premissed on the idea that we can estimate the “effect” of a 1 unit increase in `mpg` by crafting two `newdata` inputs:

``` r
mod <- glm(vs ~ mpg, family = binomial, data = mtcars)

newdata0 <- mtcars
newdata1 <- transform(mtcars, mpg = mpg + 1)

p0 <- predict(mod, newdata = newdata0, type = "response")
p1 <- predict(mod, newdata = newdata1, type = "response")

mean(p1 - p0)
# [1] 0.05680436

# equivalent with the Github version of `marginaleffects`
marginaleffects::avg_comparisons(mod)
# 
#  Term Contrast Estimate Std. Error     z   Pr(>|z|)   2.5 %  97.5 %
#   mpg       +1   0.0554   0.008327 6.653 2.8699e-11 0.03908 0.07172
# 
# Prediction type:  response 
# Columns: type, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high
```

If there is no `newdata` argument in a `predict()` method, or if we can’t easy change the kinds of predictions we generate by feeding different prediction datasets, then the entire `marginaleffects` infrastructure is useless.

Frankly, I am not a `metafor` expert, so I can’t be 100% on this. If one comes along and explains how this could be implemented, I’d be happy to help if I can.

Sorry\!

**Comment by zacrobinson5** [comment]
@vincentarelbundock thanks for the reply and no worries at all!

I am sure you came across this but not sure if this is of any help - https://www.metafor-project.org/doku.php/tips:computing_adjusted_effects?s[]=predict

Not sure if the "newmods" argument could fulfill a similar necessary function to "newdata"?

**Comment by vincentarelbundock** [comment]
Thanks, this is a nice tutorial. Unfortunately, I'm pretty sure the purpose of the `newmods` argument is different enough to make this impossible (or at least very hard, requiring someone who knows `metafor` much better than me to do the heavy lifting).
