### ISSUE TITLE
simulation based inference

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#611]

**Comment by ngreifer** [comment]
Your proposal is how `clarify` does it, i.e., `model |> sim() |> sim_ame()`. Not sure if that's best for `marginaleffects`. The purpose of doing this in `clarify` is to be able to compute many different quantities from the same simulated coefficients to retain their covariance and to be able to combine coefficients in different calls. For example, `sim_ame()` has a `subset` argument but not a `by` argument, so you have to call `sim_ame()` on the same `sim()` output object with two different subsets and then combine the resulting objects to be able to compute the difference between estimates in the subsets. But in `marginaleffects`, it's a one-and-done; the user doesn't need to retain the simulated coefficients because the covariance among estimates from different calls to, e.g., `slopes()`, is never used.

So my preference (and what I think will be easiest for both you and the user) is simply to have a `mode`- or `method`-type argument that selects whether delta-method or simulation-based inference is used. If simulation-based inference is used, the original function (e.g., `avg_comperisons()`, `avg_slopes()`) draws coefficients from the multivariate normal with the covariance supplied to the `vcov` argument like usual and does the whole thing internally. I don't think the user needs to see or create the simulated coefficients themselves (unlike in `clarify` because the philosophy is different).

So I think the user should specify
```r
mod <- lm(y ~ x, data = data)

cmp <- avg_comparisons(mod, ci_method = "simulation", iter = 1000)
```
The draws can be retained as an attribute for plotting, as you have now, but the draws of the regression coefficients are gone. My argument is that this is okay; there is no facility in `marginaleffects` for comparing quantities in two separate calls to a function that computes a quantity, so there is no need to retain that function for simulation-based inference, even though it would be possible.

The above is how `margins` does it, with `vce` argument controlling variance estimation, and can be set to `"delta"` or `"simulation"`. I think `margins` uses the standard deviation of the posterior, though, to compute Wald CIs rather than using quantiles, though.

**Comment by vincentarelbundock** [comment]
All very useful stuff.

Agreed on naming.

FWIW, I think the implementation I initially suggested would probably be a tiny bit easier than new arguments.

We can preserve `coefmat` if we want as an attribute, so we could use the same simulated coefficients in two calls:

```r
mod_sim <- simulation_inference(model)
predictions(mod_sim, newdata = datagrid(D = 1))
predictions(mod_sim, newdata = datagrid(D = 0))
```

Is there any situation at all where this would be useful?

I know it's a bit ridiculous, but I'm kind of hung up on not adding new arguments for this. This is already two new args (a 20% increase in `slopes()` 😉), and i worry that there will be a need for more options. Have already been mentioned: using quantiles vs. standard deviation of the posterior, reporting median vs. original estimates. I worry that to give a feature complete experience we'll need to add some more. And then we're stuck with 4 arguments that are there just to implement a feature that serves a very small percentage of the user base.

Having a seprate `simulation_inference()` function allows us to expand without "polluting" the interface for the core functionality.

Still open to arguments, but that's my bias...

**Comment by ngreifer** [comment]
> Is there any situation at all where this would be useful?

I mean, in `clarify` I claim it could be useful, but I think the infrastructure in `marginaleffects` already allows the user to specify `datagrid(D = 0:1)` and use the `hypothesis` argument to compare quantities. So as long as the user thinks ahead about exactly what they want to compute and test, they don't need to retain the coefficient matrix.

I like your solution and am coming around to it. I guess I'm surprised you want to add a whole function rather than some arguments. And I don't know if you need give the user all those options; just allow quantiles and the original estimate. If the user wants more, they have the posterior. The only extra arguments I'm imagining are `ci_method` and `iter` for controlling the number of iterations (more is always better, but slower).

Also, I know this is an esoteric method, but I think it is only so because it isn't available in software yet (other than `clarify`). I think this should be the default for the nice properties it has over the delta method (doesn't assume normality, no approximation to the variance, intervals respect bounds and are invariant to convex transformations of parameters). Its main disadvantages are that it takes longer, involves randomness, and doesn't produce p-values (same disadvantages as Bayesian). (For p-values, `clarify` inverts the confidence interval to find the largest confidence level that excludes the value of the parameter under the null.)

When this is coded up, it might be nice to run a study comparing the two methods in cases expected to better suit either of them (e.g., a parameter linear in the coefficients vs. a highly nonlinear, bounded parameter). My guess is that CIs will be just slightly wider for the simulation CIs but they will uniformly outperform the delta method in coverage (also in your example the simulation CI is actually smaller!).

**Comment by vincentarelbundock** [comment]
FYI, I created a new branch here:

https://github.com/vincentarelbundock/marginaleffects/pull/615

I would be very interested to know if you see some missing features, and if you can think of a way to test the results against `clarify` or other external benchmark.

As discussed, I now return the original estimates and `std.error` as standard deviation of the draws.

> I think margins uses the standard deviation of the posterior, though, to compute Wald CIs rather than using quantiles, though.

Is this what you recommend? My intuition is to take quantiles, because this gives us correctly bounded prediction CIs, but I don't know what theory says.

I added examples to the vignette here:

https://github.com/vincentarelbundock/marginaleffects/pull/615/files#diff-67ea9e3539b92d33876031bef365705876f02d1724a64434d22521e140acb88aR150

I also added documentation and a bibliography to the `R/inference.R`. Install the branch and type `?inference`

I'm not sure `inference()` is the right function name, but the nice thing about having something relatively generic is that we could eventually think about expanding this to include some convenience options for bootstrap.

>  I think this should be the default for the nice properties it has over the delta method (doesn't assume normality, no approximation to the variance, intervals respect bounds and are invariant to convex transformations of parameters).

As I told you on Zoom, I'm a 100% sold on the idea of implementing this, and I think it's cool and potentially useful. But here's some pushback just because I like arguing: 

K-R also assume normality, but they do so at the simulation stage when calling `MASS::mvrnorm`. Delta approximates using calculus tools, K-R approximate using RNG, and it's not clear to me *ex ante* which approximation will be noisier in any given case. In GLM models we already backtransform predictions to respect the bounds of Y, and this benefit doesn't really apply for contrasts or slopes, so scope of gains are relatively limited.

But again, I like this feature a lot and think it could be useful.

**Comment by vincentarelbundock** [comment]
FYI, this is merged and the function is (temporarily?) named `inferences()` to match the plural of all the other functions. Would be happy to consider alternative names that would eventually work for bootstrap too.

And the section of the vignette is live on the new development docs website: https://vincentarelbundock.github.io/marginaleffects/dev/articles/uncertainty.html#simulation-based-inference

**Comment by vincentarelbundock** [comment]
Bootstrap support with `boot` and `rsample` is now implemented. There is also a standalone vignette here: 

https://vincentarelbundock.github.io/marginaleffects/dev/articles/bootstrap.html

**Comment by ngreifer** [comment]
This is really cool and ambitious and really kicks the package up a notch. Nice job!

I think the interface is cool in that it makes things clean and easy to maintain, though I will say it is a little counterintuitive at first glance. It seems like you pass a model fit to `inferences()`, which would suggest that some type of inference is being made, but really `inferences()` just tags the model with metadata for the estimation functions to use. From a user perspective, I feel that those arguments belong in the estimation functions. I know you don't like adding so many arguments, but my sense is that users don't mind as long as they are documented well (and you can share documentation across functions using Roxygen, so the documentation itself isn't a burden).

Another option would be to use `inferences()` after the estimation function, which I think would also be more natural for users, e.g., with `lm()`, we estimate the model parameters and then use `summary()` afterward to do inference. If you want the delta method to be the default without calling `inferences()` after, you could run a check to see if the estimation function is being piped into (i.e., is the input to) `inferences()`. I'm imaging something like the following:

```
mod |> comparisons() |> inferences()
```

where

```
mod |> comparisons()
```

is equivalent to 

```
mod |> comparisons() |> inferences(method = "delta")
```
This is just an idea, not something I feel strongly about, but just something to consider as you work out the details.

If you're going down this road, here are a few things you might consider adding:
* Fractional weighted bootstrap using my `fwb` package, which has a near-identical interface to `boot::boot()`. The function `fwb::vcovFWB()` demonstrates how to bootstrap a model-fitting function after it has already been called.
* The cluster bootstrap (i.e., bootstrapping clusters instead of units); you could use the `vcov` argument to set the clustering variables like you currently do to request cluster-robust SEs. `sandwich::vcovBS()` and `fwb::vcovFWB()` both use this interface so it would be easy to adapt.
* I know this is just an initial draft of the functionality, but it would really speed things up to sanitize all the arguments before they are passed to the bootstrapping function so they are not sanitized each time. This might involve having an internal function e.g., `.comparisons()`, which only accepts sanitized arguments and is called in each bootstrap instead of calling `comparisons()` each time.

This looks awesome. Happy to help how I can if you have anything I can provide input on.

**Comment by ngreifer** [comment]
Also, in response to your comments about simulation-based inference:

I absolutely think the quantiles should be used, not the Wald CIs from the standard deviation of the posterior. I do allow this as an option in `clarify`, but I think only the quantiles should be used. It seems like there is room for some exploration on how to compute the CIs, e.g., using Bayesian or bootstrap methods. I think the simple quantile method is enough, though.

Although the method requires normally distributed coefficients, I believe the delta method also assumes this. That is, if the coefficients weren't normally distributed, the delta method would not yield asymptotically normal estimates either. So this is an assumption that both methods share, but also one more tenable in my opinion.

**Comment by vincentarelbundock** [comment]
Great!

Re: order `model|>predictions()|>inferences()`. This is much more intuitive and an *excellent* idea. I will definitely implement it that way.

I agree that it might be more intuitive for users to have arguments in the main function. One of the benefits of having it seperate is that we often want to pass additional arguments to the `predict()` method *and* also to the `boot::boot()` function. The `...` from `predictions()` are pushed to `predict()`, and the `...` from `inferences()` are pushed to `boot::boot()`. This simplifies the backend implementation considerably.

In any case, I think I'll release a very with the new order very soon, and clearly mark it as "experimental" in the docs and on the website. Hopefully I get some feedback and we can iterate on the design from there, doing our best to keep backward compatibility.

Moving to more specific issues instead of broad discussion:

* Bootstrap schemes: https://github.com/vincentarelbundock/marginaleffects/issues/617
* Call order: https://github.com/vincentarelbundock/marginaleffects/issues/618

**Comment by vincentarelbundock** [comment]
On sanity checks, I'd have to do profiling, but my guess is that sanity checks are problem <2% of total run time. Skipping would surely be more efficient, but my gut says this is not a big deal.
