### ISSUE TITLE
Some potential speed improvements

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#628]
I noticed a few places in the code where I think the speed could be improved. If you think it's worth implementing and you don't have time for this, I can maybe make a PR.

### Delete/select columns by reference

Here for example:
https://github.com/vincentarelbundock/marginaleffects/blob/11d66dabd7c0636051a65c6ba0589629f1258d3c/R/comparisons.R#L463

``` r
library(data.table)

# Make a big data.table
tmp <- vector("list", length = 1e6)
for (i in 1:1e6) {
  tmp[[i]] <- mtcars
}
test <- rbindlist(tmp)

cols = names(test)[1:2]

bench::mark(
  assign = {
    test <- test[, ..cols, drop = FALSE]
    head(test)
  },
  ref = {
    test[, setdiff(names(test), cols) := NULL]
    head(test)
  }
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 assign        152ms    152ms      6.58     488MB     6.58
#> 2 ref           286µs    335µs   2405.       199KB    10.5
```

But need to be careful if data is modified by reference

### Use `collapse::fduplicated()`

Only available in devel version of `collapse` for now (and `duplicated()` used only once in the code):

``` r
set.seed(123)
test <- sample(1:10, 1e7, replace = TRUE)

bench::mark(
  duplicated(test),
  collapse::fduplicated(test)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                       min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                  <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 duplicated(test)              87.7ms   95.4ms      9.85     166MB     9.85
#> 2 collapse::fduplicated(test)   21.1ms   24.1ms     33.0       86MB    11.6
```
I hope it's useful

---

I realized afterwards that `collapse` is suggested only, not imported by `marginaleffects` so it would add a dep

**Comment by vincentarelbundock** [comment]
Ha, that's a cool trick!

Yes, I'm definitely happy to merge performance PRs. Just two things I'll say:

1. I strongly prefer to *not* add any more dependencies to the package. Currently, `collapse` is an "optional" that only gets called when dealing with matrices of posterior draws. Since that use is circumscribed to bayesian models, it's easy to call `insight::check_if_installed("collapse")` once, and only for those models. I wouldn't want to use a `collapse` function in the "core" code unless it really brings massive speed improvements.
2. I think it might be worth it to do a bit of profiling (with `profvis` or other). My general sense is that when `marginaleffects` takes a long time to run, it's nearly always because it spends a lot of time calling `predict()`. When `vcov=TRUE`, we need to call `predict()` twice per coefficient in the model, so that can take a very long time (`vcov=FALSE` is generally much faster). If, as is often the case, 98% of the wall time is spent outside of `marginaleffects`, microseconds won't cut it. Obviously, faster software is better, and I'd be very grateful for your help. But I know you're busy, so I'd just encourage doing a bit of profiling to avoid premature optimization.

**Comment by etiennebacher** [comment]
1. Sure, I get it, I'm now wondering if calling `insight::check_if_installed()` will cancel the speed gain in 99% of the cases

2. Yeah I did some profiling on `slopes(mod, vcov = FALSE)` with the example from [here](https://vincentarelbundock.github.io/marginaleffects/articles/performance.html) and I saw that the `[.data.table` calls take some time and didn't seem too hard to improve. I try not to spend a lot of time on this and I don't know the codebase of the package enough to improve it "in depth" anyway. I suppose the best way to make `marginaleffects` faster is to improve `insight`?

**Comment by vincentarelbundock** [comment]
Improving `insight` is certainly a good way to help a lot of downstream pacakges, including `marginaleffects`!

But I really don't want to discourage you to make some minor improvements now! The best way to get familiar with a code base is to start with small things :)
