### ISSUE TITLE
Dates?

### ISSUE THREAD

**Issue by ASKurz** [vincentarelbundock/marginaleffects#646]
Hey @vincentarelbundock, would you consider including dates and possibly author names in your nice vignettes? That information would make for better citations.

**Comment by vincentarelbundock** [comment]
That's a good suggestion. I'm thinking about converting the whole website to Quarto book similar to your Rethinking. But there's a lot to figure out (e.g., how to insert Function documentation and Changelog), so that's probably a 6-12 months time horizon.

Until then, the date should probably be the latest Git push (2023-02-03).

I wrote all the vignettes, except that Andrew Heiss co-authored the vignette on `brms` and Arthur Albuquerque wrote most of the Logistic Regression vignette.

**Comment by ASKurz** [comment]
Oh, cool. Yeah, you're at the point where the **marginaleffects** framework could fill an ebook, for sure. In the meantime, your comment here can tide me over with the documentation.
