### ISSUE TITLE
Delta error not available for ordered beta regression in glmmTMB

### ISSUE THREAD

**Issue by saudiwin** [vincentarelbundock/marginaleffects#663]
As of 0.9.0, package will not calculate `delta` style standard errors for the ordered beta family in `glmmTMB` (supported as of Nov 2022):

```
library(ordbetareg)
library(glmmTMB)

data("model_data")

# need to normalize first to 0 and 1

model_data$therm_norm <- (model_data$therm - min(model_data$therm))/(max(model_data$therm) - min(model_data$therm))

glmm_tmb_fit <- glmmTMB(therm_norm ~ approval + (1|region),
                        data=model_data,
                        family=ordbeta(),
                        start=list(psi = c(-1, 1)))


avg_slopes(glmm_tmb_fit)

```

produces the error:

```
Error: Unable to compute standard errors for this model.
```

There doesn't seem to be any reason why the delta method wouldn't work for this model if it works for other glmmTMB models.

Using the `inference` function does permit standard error calculation with bootstrapping. When I try the simulation option, I get a different error:

```
avg_slopes(glmm_tmb_fit,vcov = FALSE) %>% inferences(method="simulation")
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
```

Would love if this could be fixed!

**Comment by vincentarelbundock** [comment]
Thanks for raising the issue. Should be fixed on Github.

Frankly, I'm kind of surprised this worked before, since the "broken" part of the code has not changed for many months.

BTW, I'm not that familiar with `glmmTMB` models, and would be grateful if you could opine on a quick think.

To compute standard errors with the delta method, we need to take derivatives of the predictions *with respect to the model coefficients*. This entails modifying the internals of the model object to increment the value of one coefficient by a tiny amount. In your model, `vcov()` generates a 2x2 matrix, so there are two coefficients to increment. Two questions:

1. The code I use to modify the internals of `glmmTMB` objects makes some assumptions about the order in which parameters are stored. Is that safe? https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_glmmTMB.R#L44
2. The resulting standard errors only account for the covariance structure among the fixed effects of the model, that is, only for the parameters whose uncertainty is printed when calling `vcov(fit)`. Is that what users would expect?
