### ISSUE TITLE
Speed up data processing in `get_contrast_data()`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#744]
In an earlier conversation (#611), you said 

> On sanity checks, I'd have to do profiling, but my guess is that sanity checks are <2% of total run time. Skipping would surely be more efficient, but my gut says this is not a big deal.

I've been experimenting with moving the `WeightIt` documentation to use `marginaleffects`. Bootstrapping is a lot more important to IPW, and unfortunately the bootstrap functionality in `marginaleffects` can't be used because the weights need to be estimated in each bootstrap sample before they are supplied to the outcome model.

I have found that the processing of the data done by `avg_comparisons()` takes the vast majority of the time in each bootstrap replication, mostly because `get_model_matrix()`, which is called by `get_model_matrix_attribute()`, which is called by `get_contrast_data()`, uses the very slow `insight::get_modelmatrix()` (which is slow because it calls `get_data()`). I'm wondering if there is a way to speed that up. You're right that it's not the sanitizing itself, but it is a critical step in data processing that has to occur every time the function is run. I'm working with `lm` objects, which appear to be treated different from some other models.

**Comment by vincentarelbundock** [comment]
I don't have a good mental model of the bootstrap code right now (forgot). Do you think there's anything I can do to push forward the weights and update the models internally?

Re: model matrix. LM and GLM models are now treated differently: we have our own prediction code which does matrix multiplication from MM and b using RcppEigen. Before, profiling showed that predict() took up most of the time, but under the hood, most of that was building the model matrix. Now we see that get_modelmatrix takes up most of the time, but it's still much faster than before.

As you note, we may still be able to improve the time. A first try would be to substitute the insight::get_modelmatrix() call by:

model.matrix(model, data = newdata)

This should be faster, but it's less general because some models don't support the data argument. So need to check if inherits from lm or glm before.

There was an ice storm in Montreal and I'm out of internet on my computer, but this would be pretty easy to try out, I think. Let me know if you try and see a difference (or not)

**Comment by vincentarelbundock** [comment]
I pushed a change using `stats::model.matrix` for `lm()` and `glm()` models. 0.11.0.9008 (now on Github) is now ~3 times faster than 0.9.0 for some models and some calls. For example:

```r
library("marginaleffects")

N <- 1e4
dat <- data.frame(
  y = rnorm(N),
  x1 = rnorm(N),
  x2 = sample(letters[1:10], size = N, replace = TRUE)
)
fit <- lm(y ~ x1 + x2, dat)

bench::mark(avg_comparisons(fit))[, 1:5]

# 0.11.0.9008
# > bench::mark(avg_comparisons(fit))[, 1:5]
# # A tibble: 1 × 5
#   expression                min   median `itr/sec` mem_alloc
#   <bch:expr>           <bch:tm> <bch:tm>     <dbl> <bch:byt>
# 1 avg_comparisons(fit)    507ms    507ms      1.97     361MB

# 0.9.0
# > bench::mark(avg_comparisons(fit))[, 1:5]
# # A tibble: 1 × 5
#   expression                min   median `itr/sec` mem_alloc
#   <bch:expr>           <bch:tm> <bch:tm>     <dbl> <bch:byt>
# 1 avg_comparisons(fit)    1.51s    1.51s     0.663    1.22GB
```

**Comment by vincentarelbundock** [comment]
Also,  memory use is nice.
