### ISSUE TITLE
Feature request: add variable names from `by` to columns

### ISSUE THREAD

**Issue by shirdekel** [vincentarelbundock/marginaleffects#758]
When using the `by` with multiple variables we end up with a `by` column with concatenated text. Is it possible to instead (or also) have columns that indicate the relevant variable levels? This will make it easier to subsequently filter for required rows, rather than filtering the 'by' column using regex.

For instance, in the below example, it would be good to have columns for `am` and `group`. The `am` column would have either a zero or one, and the `group` column would have either `4,6` or `8`.

```r
library(nnet)
library(marginaleffects)

dat <- mtcars
mod <- multinom(factor(cyl) ~ mpg + am, data = mtcars, trace = FALSE)
by <- expand.grid(
  am = 0:1,
  group = as.character(c(4, 6, 8))
) |> transform(by = ifelse(group %in% 4:6, paste(am, "4,6"), paste(am, "8")))

predictions(mod,
  newdata = datagrid(am = unique),
  by = by,
  byfun = sum
)
```

**Comment by vincentarelbundock** [comment]
This is not possible because the content of by column is arbitrary. In your example, the fields are separated by a single space, but other users may use a different scheme like | or -. So marginaleffects cannot reliably and generally split the user-supplied column.

However, since you *know* the format in your specific call, it is trivial for you to separate the by column using a function like this:

https://tidyr.tidyverse.org/reference/separate.html
