### ISSUE TITLE
Website: changelog page is broken

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/marginaleffects#799]
Probably due to 32d173f82bdd792c693be926f8edecc2357de590

https://vincentarelbundock.github.io/marginaleffects/dev/news/index.html

![image](https://github.com/vincentarelbundock/marginaleffects/assets/52219252/c9d5272b-c0ac-4d1d-b011-706c9b8180f7)

**Comment by vincentarelbundock** [comment]
Thanks @etiennebacher 

I'm actually working on a total website revamp at the moment. I'm trying to use Quarto because I need both a website and a PDF (for day job-related reasons).

I'd be really curious to know what you think about the current version. I added you as a collaborator on the private repo, so feel free to open issues or make changes directly (no pressure, obviously). Here's the current live version:

https://vincentarelbundock.github.io/mfxbook/
