### ISSUE TITLE
Feature request: Transform estimate and confidence interval from `hypotheses()`

### ISSUE THREAD

**Issue by snhansen** [vincentarelbundock/marginaleffects#832]
When using `hypotheses()` to perform linear combinations of parameters, we'll get an estimate and confidence interval on the link scale. It would be nice to be able to backtransform these into estimates and confidence interval on the "original" scale.

For instance, this code

    library(marginaleffects)
    mtcars |>
      glm(am ~ mpg, family=binomial(link = "logit"), data = _) |>
      hypotheses("10*mpg = 0")

will give you an estimate and confidence interval for the log-odds-ratio for a 10 unit increase in `mpg`, and it would be nice to have an option whereby the result is exponentiated to yield the odds-ratio.

**Comment by vincentarelbundock** [comment]
Thanks for the feature request.

The problem is that you’ve hit on one of the few hypotheses where the correct backtransform is obvious. The hypothesis argument can be used to estimate arbitrary functions of estimates quantities and contrasts. In general, contrasts cannot be back transformed (except in special cases), and it would be very difficult to find the appropriate inverse function from strings. So I am afraid this is out of scope for the package.

of course, you know that the marginaleffects objects are just data frames. So it is really trivial to add a single mutate() or transform() call to backtransform when the analyst knows how.

**Comment by snhansen** [comment]
Ah, that's completely understandable. I'll be using it in my teaching and was thinking that it would be easier for the student to just pass an option rather than having to do it manually. But you're right, it's not a big hassle to manually do the transformations except that we'll have to write the function thrice ;-)

In any case, thanks for the fast repsonse, Vincent!

**Comment by vincentarelbundock** [comment]
Would be curious to hear what your students think and what problems they run into!
