### ISSUE TITLE
Feature request: Ability to specify color, linetype and linewidth in `plot_predictions()` with only one condition.

### ISSUE THREAD

**Issue by snhansen** [vincentarelbundock/marginaleffects#858]
Say I'm interested in the association between a continuous X and Y. I can get a nice plot of the predictions together with a scatterplot using 
```
plot_predictions(model, condition = "x", points = 1)
```

However, if there are many points it can be hard to distinguish the prediction line from the dots. Lowering the transparency of the dots by the `points`-argument can sometimes help out but not always. So it would be nice to be able to specify the color, linetype and linewidth of the prediction line in this case.

I know I could do the plot myself using e.g.

```
plot_predictions(model, condition = "x", draw = FALSE) |>
ggplot() + 
geom_line(aes(x = x, y = estimate), color = "red", linewidth = 1.25) +
geom_point(data = org_data, ...)
```
but I would have to refer to two data frames here (the original data for the points and the predicted data for the line), so this is not ideal imo.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the feature request.

I thought about this a lot (not just since yesterday), and have decided that I would not add many more *aesthetic* features to `plot_*()` functions. The problem is that there are just too many things that one might want to control: size of dots, color of dots, size by group, color by group, alpha of ribbon, size of pointrange dots and lines, rug plot size, etc.

It just doesn't end, and I don't want to have a user interface with 50 different arguments. And frankly, I don't have time to implement and maintain such a broad feature set. So the `plot_*()` functions will have to remain relatively skeletal, and mostly intended for exploration. Users who want to fine-tune plots for publication are encouraged to do `draw=FALSE` and build a plot themselves.

I know this might be disappointing, but
