### ISSUE TITLE
How can the plot_slopes function simultaneously set different shapes and colors for different points to meet the requirements of black and white printing?

### ISSUE THREAD

**Issue by acrackedpolystyreneman** [vincentarelbundock/marginaleffects#910]
How can the plot_slopes function simultaneously set different shapes and colors for different points to meet the requirements of black and white printing?

I do not understand this:

"## condition- Conditional slopes

### Named list (max length 3): List names correspond to predictors. List elements can be:

- Numeric vector
- Function which returns a numeric vector or a set of unique categorical values
- Shortcut strings for common reference values: "minmax", "quartile", "threenum"

**Comment by vincentarelbundock** [comment]
try the `gray` argument

**Comment by acrackedpolystyreneman** [comment]
王相麾已经收到，谢谢你的来信~

**Comment by vincentarelbundock** [comment]
the `plot_slopes()` (and analogues) are intentionally designed as very simple function because (a) the needs of users are endless, and (b) it is usually trivial to produce the exact plot we want using a couple lines of `ggplot2`. If the `gray` argument does not do what you want, I recommend using `draw=FALSE` and feeding the (already well-formatted) data frame to `ggplot()`. See here for some examples: https://marginaleffects.com/articles/plot.html#customization
