### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by lachanskim** [vincentarelbundock/marginaleffects#925]
I am sure you have thought of this, but just in case, it would be helpful to support parallelization or parallelized functions when testing multiple hypotheses. There are a number of ways this could be done using the future framework.

**Comment by vincentarelbundock** [comment]
Typically, you want to parallelize the outer-most loop possible. The computation of multiple hypotheses is actually nested pretty deeply in the code logic. One "outer-most" where it would make sense to parallelize is in the calculation of standard errors, since we need to run this once for every coefficient in the model. In other words, we need to compute each of hte hypothesis test for each coefficient to get the standard errors.

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_jacobian.R#L48 

I've made some attempts to parallelize this, but haven't had much luck. My sense is that parallelization matters much more for big data, but that big data also involves a lot of overhead with passing data frames to the cores. So often times it's a wash.

I will probably try again at some point. In the meantime, if anyone else wants to give this a shot, I'd be really curious to hear about their experience.

**Comment by vincentarelbundock** [comment]
BTW, if you are really working with massive data, you probably want to compute the marginal effects only on unique rows, and then use the `wts` argument (perhaps coarsening some variables or taking averages). Your results will likely be indistinguishable and much faster to compute.

**Comment by lachanskim** [comment]
Thanks, this is a cool trick I knew about but had forgotten while deep in my dissertation. Great idea.
