### ISSUE TITLE
Weights for IPW

### ISSUE THREAD

**Issue by chloekrakauer** [vincentarelbundock/marginaleffects#926]
[IPW_weights_bug_2023October11.pdf](https://github.com/vincentarelbundock/marginaleffects/files/12874704/IPW_weights_bug_2023October11.pdf)
Hi there,

My research group is aiming to use avg_comparisons() to estimate marginal effects of a binary covariate using output from different regression models that allow for missing data. Some of these regression models use weights. We have found that while the existing function avg_comparions() is compatible with some weighted regression models, there is an assumption made about the weights within the function that is incompatible with standard IPW: that the weights have an average of 1 among the observed cohort. This assumption is generally not true in standard IPW regression (it is approximately, but not exactly true). The issue seems to be the passing of weights and estimates to the weighted.mean() function, which automatically normalizes the weights in the observed population. 

NEW: I have added a new vignette with a simple generated dataset that illustrates the bug attached (RMarkdown output). Please let me know if you have any questions about it (chloe.a.krakauer@kp.org). I'm also happy to send the R code separately.

My research group was formulated for a Food and Drug Administration project with the aim of finding the best methods of handling missing data in continuous monitoring of pharmaceuticals using electronic medical records. 

https://www.sentinelinitiative.org/methods-data-tools/methods/subset-calibration-methods

We will disseminate all the methods used to estimate conditional and marginal effects in both Food and Drug Administration manuals and to the broader research community via publications. We are hoping to use your package for all marginal effect estimation and suggest use of the package in our publications and internal manuals.

I'm very happy to answer any follow-up questions and am very willing to work with your team to get the issue resolved. Thanks so much.

-Chloe Krakauer, PhD
chloe.a.krakauer@kp.org
Kaiser Permanente Washington Health Research Institute

**Comment by vincentarelbundock** [comment]
@chloekrakauer, thanks a lot for raising this issue and for putting together this very useful notebook. I am *very* interested in working with you to resolve this. I'll be on a work retreat for a few days, but will look into this when I come back.

@ngreifer This may be in your wheelhouse. I'd be very curious to know what you think of the notebook at the top of the original post. Do you have any recommendations?

Some options may be:

1. Add a new `wts_norm=FALSE` argument, which switches away from `weighted.mean()`. This is perhaps simplest for users, but I'm not a big fan since I tend to lean toward general solutions rather than application-specific ones.
2. Add `byfun` arguments to the `comparisons()` function. Note that `predictions()` already has this argument. Currently, this defaults to `mean()` when `wts=NULL` and `weighted.mean()` otherwise. The syntax could look like:
	- `avg_comparisons(mod, wts = "w", byfun = \(x, w) x %*% w)`
	- `avg_comparisons(mod, wts = "w", byfun = "some_intuitive_shortcut_label")

I don't find the syntax in 2 very elegant. Maybe there's something better?
	
These are just initial reactions, and I haven't thought about this seriously, so I'd very much welcome input on a solution.

**Comment by ngreifer** [comment]
My immediate reaction is to push back on the idea that the estimator in `marginaleffects` is "wrong". It is a Hajek estimator, which is consistent and generally more precise than the Horvitz-Thompson estimator. For example, [Lunceford & Davidian (2004)](https://doi.org/10.1002/sim.1903) found that the HT estimator performed uniformly worse than the Hajek and other estimators in their studies. A benefit of the Hajek estimator is that it is invariant to arbitrary scaling of the weights, which is important when using any weighting method other than IPW (e.g., entropy balancing).

I agree that there maybe should be an option to request the HT estimator, but I don't think it is wrong to omit it or treat it as a niche option primarily for comparison purposes. I don't know if I love the `wts_norm = FALSE` option because that suggests the HT estimator is the natural estimator and Hajek is a normalization rather than that the usual estimator is simply the standard formula for a weighted mean and HT is a specific estimator for use with IPW. I don't know if `byfun` is the best name for this argument since one isn't really using `by` here; it's a function specifically for computing a mean that incorporates weights.

For a user interface, I don't know which is the better option; my impression is that this is a somewhat niche problem, and `marginaleffects` doesn't need to accommodate every single scenario. On the other hand, I agree that it would be really nice if there was a general solution that allowed users to request whatever they want, even if they have to work for it. From a documentation perspective, one idea would be to allow some arguments to be passed to `...` and have those arguments documented on a separate help page for more advanced customization of the estimates. I do this with [`cobalt::bal.tab()`](https://ngreifer.github.io/cobalt/reference/bal.tab.html), which has so many options that documenting them all on a single page would be overwhelming, but I allow interested users to delve into more advanced arguments on a [separate help page](https://ngreifer.github.io/cobalt/reference/display-options.html) if they choose. I don't know if this is a great approach, but I think it helps solve the documentation/argument overload problem while allowing for flexibility for advanced users.

**Comment by vincentarelbundock** [comment]
I'll let @chloekrakauer react to the statistical points (on the bus and can't engage fully), but how about an argument called `aggregation` with default value:

`aggregation=ifelse(is.null(wts), mean, weighted.mean)`

(Argument value in the signature depends on the other arg value)

This would be consistent with the vocabulary in our JSS submission.

**Comment by vincentarelbundock** [comment]
Now that I think about it, we can almost certainly do this already with a custom function in the `comparison` argument. Will illustrate later.

**Comment by chloekrakauer** [comment]
Thanks so much for pursuing this so quickly, I (and the rest of the team) really appreciate it.

@ngreifer, thanks so much for sharing the information about the HT vs. Hajek estimators. As for the estimator that is considered the "default", I defer entirely to you. My immediate inclination is that having an option for HT, even if the Hajek estimator has superior properties as you outline above, is ideal. For reference, our team is aiming to compare qualities of standard-practice estimators, particularly those employed by scientists in medical studies; from what I understand, HT is still used most-often. Our aim is to highlight benefits and pitfalls of standard procedures for methods of handling missing data and the resulting conditional and marginal estimates, the latter of which could certainly include the relative qualities of the weighting approaches as you outline above. In this latter case, we would need to illustrate relative strengths of the Hajek estimator (to the HT estimator) by estimating both. I'll consult with Thomas Lumley and others on our team about which estimators to pursue, and if we should simply use the Hajek estimator with IPW regression output (but given our prior conversations, my inclination is to pursue either HT or both HT and Hajek); my own understanding on this subject is superficial.

In the meantime, @vincentarelbundock, we greatly appreciate the option of using an HT estimator if possible. I'll reply soon with feedback from Dr. Lumley and the rest of my team.

**Comment by vincentarelbundock** [comment]
Here’s what I had in mind. In the code below, I define a new function called `or()`, and feed it to the `comparison` argument of the `avg_comparisons()` function. `or()` takes 3 arguments with obvious meanings: `hi`, `lo`, and `w`. This allows us to replicate the manual calculate exactly (with standard errors, etc.)

One minor challenge is that `or()` hardcodes the denominator on `nrow(data)`. We could re-write the function to use `length(hi)` as denominator, but that produces a different result. Presumably that’s linked to the missing data aspect of your project.

I could pretty easily add a string shortcut like `"differenceavg"` to correspond to the custom `or()` function used below, but (1) I’m not sure what procedure guarantees that we get the right deonomiator, and (2) not sure what an informative label would be for that function. Any thoughts, @chloekrakauer ?

## Old code

``` r
library(mvtnorm)
library(marginaleffects)
set.seed(33)

generating_data <- function(N) {
    # Producing Z, W, and latent X (cutpoint used later to determine yes/no for binary indicator)
    lowcor <- .1
    midcor <- .4
    highcor <- .7
    gencor <- .2
    corMat <- matrix(gencor, nrow = 3, ncol = 3)
    corMat[2, 1] <- corMat[1, 2] <- lowcor ### cor (X,Z)
    corMat[3, 1] <- corMat[1, 3] <- midcor ### cor (X,W)
    varMat <- corMat
    diag(varMat) <- 1
    XZW <- rmvnorm(N, rep(0, 3), varMat)
    latentX <- XZW[, 1]
    Z <- XZW[, 2]
    W <- XZW[, 3]
    pX <- 0.4
    X <- ifelse(latentX < quantile(latentX, p = pX), 1, 0)
    # Now, generating Y using generated X, Z, and W with logistic model.
    beta0 <- -2.4
    betaX <- log(1.5)
    betaZ <- -log(1.3)
    betaW <- -log(1.75)
    Xbeta <- beta0 + betaX * X + betaZ * Z + betaW * W
    expit <- function(x) {
        exp(x) / (1 + exp(x))
    }
    Y <- ifelse(runif(length(X)) < expit(Xbeta), 1, 0)
    # Finally, supposing W is not observed for some individuals.
    alpha0 <- -.67
    alphaX <- log(1.5)
    alphaZ <- log(2.5)
    XbetaM <- alpha0 + alphaX * X + alphaZ * Z
    miss <- ifelse(runif(length(X)) < expit(XbetaM), 1, 0)
    observed <- 1 - miss
    W_obs <- ifelse(miss == 0, W, NA)
    data <- data.frame(Y, X, Z, W, W_obs, observed)
    return(data)
}
data <- generating_data(N = 10000)

# Estimating probability of being observed, compute IPW weights
miss_fit <- glm(observed ~ X + Z, family = "binomial", data = data)
ipw_wt <- 1 / predict(miss_fit, type = "response")

# get IPW estimator and robust SE
data_cc = data
data_cc$ipw_wt <- ipw_wt
data_cc <- data_cc[data_cc$observed == 1, ]
ipw_fit <- glm(Y ~ X + Z + W_obs,
    family = "quasibinomial",
    data = data_cc, weights = data_cc$ipw_wt)


data_0 <- data
data_0$X <- 0
data_1 <- data
data_1$X <- 1
preds_0 <- predict(ipw_fit, newdata = data_0, type = "response", na.action = na.omit)
preds_1 <- predict(ipw_fit, newdata = data_1, type = "response", na.action = na.omit)
weights <- weights(ipw_fit)
mu_1 <- sum(weights * preds_1) / nrow(data)
mu_0 <- sum(weights * preds_0) / nrow(data)
marginal_rd_calc <- mu_1 - mu_0
marginal_rr_calc <- mu_1 / mu_0
marginal_or_calc <- (mu_1 / (1 - mu_1)) / (mu_0 / (1 - mu_0))
```

## New code

``` r
or <- function(hi, lo, w) {
    mu_lo <- sum(lo * w) / nrow(data)
    mu_hi <- sum(hi * w) / nrow(data)
    (mu_hi / (1 - mu_hi)) / (mu_lo / (1 - mu_lo))
}

comparisons(ipw_fit,
    wts = weights,
    comparison = or,
    variables = "X") |> print(digits = 7)
# 
#  Term Contrast Estimate Std. Error        z Pr(>|z|)     S    2.5 %   97.5 %
#     X     1, 0 1.477961  0.1239932 11.91969  < 0.001 106.4 1.234939 1.720983
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
# Type:  response

marginal_or_calc
# [1] 1.477961
```

**Comment by ngreifer** [comment]
Maybe use `sum(w > 0, na.rm = TRUE)` instead of `nrow(data)`, since that should only include units with positive weights (which are the only units included in the weighted mean), and it doesn't hardcode `data`.

**Comment by vincentarelbundock** [comment]
All the weights are positive, so that's equivalent to `length(hi)`

**Comment by ngreifer** [comment]
Ah, I see. One way to go would be to supply the full dataset to `glm()` instead of just the complete cases and let it use its na.action to drop the cases with missingness. Then you can try to have `avg_comparisons()` use the dataset stored in the `glm()` object's `data` argument, which contains the full dataset, rather than what `insight::get_data()` extracts, which is the model frame after dropping the observations with `NA`. That would seem to me to be the only way to extract the original sample size without hard-coding it, but I think that would create a lot of downstream complications and special cases. When you supply just the complete cases to `glm()`, there is no way to know the size of the original dataset, which is part of the HT estimator definition, from the `glm()` output alone. Another reason to favor Hajek :)

**Comment by vincentarelbundock** [comment]
Perhaps a simpler alternative is to require users to supply the full dataset (with incompletes) to the `newdata`, and to pass `newdata` to the custom function in the `comparison` argument. This behavior may be non-obvious to the user, but we can do a sanity check to force users to supply the proper arguments when this specific `comparison` is requested. This can probably be documented adequately.

Install the `ipw` branch:

``` r
remotes::install_github("vincentarelbundock/marginaleffects@ipw")
```

Restart `R` completely for the change to take effect. Then,

``` r
library(mvtnorm)
library(marginaleffects)
set.seed(33)

generating_data <- function(N) {
    # Producing Z, W, and latent X (cutpoint used later to determine yes/no for binary indicator)
    lowcor <- .1
    midcor <- .4
    highcor <- .7
    gencor <- .2
    corMat <- matrix(gencor, nrow = 3, ncol = 3)
    corMat[2, 1] <- corMat[1, 2] <- lowcor ### cor (X,Z)
    corMat[3, 1] <- corMat[1, 3] <- midcor ### cor (X,W)
    varMat <- corMat
    diag(varMat) <- 1
    XZW <- rmvnorm(N, rep(0, 3), varMat)
    latentX <- XZW[, 1]
    Z <- XZW[, 2]
    W <- XZW[, 3]
    pX <- 0.4
    X <- ifelse(latentX < quantile(latentX, p = pX), 1, 0)
    # Now, generating Y using generated X, Z, and W with logistic model.
    beta0 <- -2.4
    betaX <- log(1.5)
    betaZ <- -log(1.3)
    betaW <- -log(1.75)
    Xbeta <- beta0 + betaX * X + betaZ * Z + betaW * W
    expit <- function(x) {
        exp(x) / (1 + exp(x))
    }
    Y <- ifelse(runif(length(X)) < expit(Xbeta), 1, 0)
    # Finally, supposing W is not observed for some individuals.
    alpha0 <- -.67
    alphaX <- log(1.5)
    alphaZ <- log(2.5)
    XbetaM <- alpha0 + alphaX * X + alphaZ * Z
    miss <- ifelse(runif(length(X)) < expit(XbetaM), 1, 0)
    observed <- 1 - miss
    W_obs <- ifelse(miss == 0, W, NA)
    data <- data.frame(Y, X, Z, W, W_obs, observed)
    return(data)
}
data <- generating_data(N = 10000)
```

``` r
miss_fit <- glm(observed ~ X + Z, family = "binomial", data = data)
data$ipw_wt <- 1 / predict(miss_fit, newdata = data, type = "response")

ipw_fit <- glm(Y ~ X + Z + W_obs,
    family = "quasibinomial",
    data = data[data$observed == 1, ],
    weights = ipw_wt)

comparisons(ipw_fit,
    wts = "ipw_wt",
    comparison = "oravght",
    newdata = data,
    variables = "X") |> print(digits = 7)
# 
#  Term          Contrast Estimate Std. Error        z Pr(>|z|)     S    2.5 %   97.5 %
#     X odds(1) / odds(0) 1.477961  0.1239932 11.91969  < 0.001 106.4 1.234939 1.720983
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted 
# Type:  response
```

**Comment by chloekrakauer** [comment]
Hi @vincentarelbundock and @ngreifer, thanks so much for your continued work on this. I got in touch with Dr. Lumley, who like you, is actually more inclined towards the Hajek estimator as it turns out, but having the option of the HT estimator is appreciated (by both Dr. Lumley and myself). The first workaround provided above that uses a hard-coded nrow(data) to produce the HT estimator definitely works for me and is something I'm happy to continue using/include in our report. As for incorporating it as an option into the package, I don't have strong feelings about the best way to do that, but am happy to offer a users' perspective if it is helpful.

**Comment by chloekrakauer** [comment]
But, given the workaround option provided above, I defer to your judgment on whether it is worthwhile to incorporate the HT option into the package. 

Thanks so much again for your very quick turnaround on this, and happy to keep using the package for this project!

**Comment by vincentarelbundock** [comment]
Sounds great!

I have merged the ability to process `newdata` in the `comparison` function, which allows us to write more generic comparison functions that do not hardcode the dataset size.

However, I will *not* include a shortcut label for the HT-marginal odds ratios. As we know from above, it's still pretty easy to get, especially with the new improvement.

I also wrote a very short vignette on IPW for the website. It's really just a minimal working example with very little commentary. But if either of you have any feedback, I'm interested!

https://marginaleffects.com/articles/ipw.html

**Comment by chloekrakauer** [comment]
That's terrific, thanks so much @vincentarelbundock (and again, thanks so much for the very quick turnaround on this). Having the vignette is great! I do have one question about it (which doesn't impact the package)...should the weights be the inverse of the probability of being treated in the working example?

**Comment by vincentarelbundock** [comment]
Haha, yeah. That's what happens when I work too quickly. The website should be updated now, and I'll try to submit the updated package to CRAN in the coming days.

Thanks for raising these issues; it's very useful for me to know where to improve the package.

I'll close this now, but feel free to open a new issue if other problems/limitations arise.
